# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-18 11:10
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('commons', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='language',
            fields=[
                ('languageID', models.AutoField(primary_key=True, serialize=False)),
                ('languageName', models.CharField(max_length=256)),
                ('resourceCode', models.CharField(max_length=3)),
                ('createdOn', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'com_Language',
                'get_latest_by': 'userName',
            },
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('userID', models.AutoField(primary_key=True, serialize=False)),
                ('phoneNumber', models.CharField(max_length=15, unique=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('userName', models.CharField(max_length=100)),
                ('photoUrl', models.CharField(max_length=255, null=True)),
                ('udiseCode', models.CharField(max_length=255, null=True)),
                ('emailID', models.EmailField(max_length=100, null=True)),
                ('createdOn', models.DateTimeField(auto_now_add=True)),
                ('modifiedOn', models.DateTimeField(auto_now_add=True)),
                ('createdBy', models.ForeignKey(db_column='createdBy', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_createdBy', to='users.user')),
                ('districtID', models.ForeignKey(db_column='districtID', on_delete=django.db.models.deletion.CASCADE, related_name='user_districtID', to='commons.district')),
                ('modifiedBy', models.ForeignKey(db_column='modifiedBy', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_modifiedBy', to='users.user')),
                ('preferredLanguageID', models.ForeignKey(db_column='languageID', on_delete=django.db.models.deletion.CASCADE, related_name='user_preferredLanguageID', to='users.language')),
            ],
            options={
                'db_table': 'usr_User',
                'get_latest_by': 'userName',
            },
        ),
        migrations.CreateModel(
            name='userAuth',
            fields=[
                ('userAuthID', models.AutoField(primary_key=True, serialize=False)),
                ('loginID', models.IntegerField(unique=True)),
                ('password', models.CharField(max_length=256, null=True)),
                ('sessionToken', models.CharField(max_length=256, null=True)),
                ('lastLoggedInOn', models.DateTimeField(auto_now_add=True)),
                ('createdOn', models.DateTimeField(auto_now_add=True)),
                ('modifiedOn', models.DateTimeField(auto_now_add=True)),
                ('createdBy', models.ForeignKey(db_column='createdBy', on_delete=django.db.models.deletion.CASCADE, related_name='userAuth_createdBy', to='users.user')),
                ('modifiedBy', models.ForeignKey(db_column='modifiedBy', on_delete=django.db.models.deletion.CASCADE, related_name='userAuth_modifiedBy', to='users.user')),
            ],
            options={
                'db_table': 'usr_userAuth',
            },
        ),
        migrations.AddField(
            model_name='language',
            name='createdBy',
            field=models.ForeignKey(db_column='createdBy', on_delete=django.db.models.deletion.CASCADE, related_name='language_createdBy', to='users.user'),
        ),
    ]
