-- Insert code group for Blocks.
Insert into com_codeGroup (codeGroupID, codeGroupName, createdBy, createdOn, modifiedBy, modifiedOn)
Select 119 as codeGroupID, 'Blocks' as codeGroupName, 1 as createdBy, now() as createdOn,  1 as modifiedBy, now() as modifiedOn;

-- Insert code for blocks
INSERT INTO com_code(codeID, codeNameEn,codeNameMr,codeGroupID,createdBy,modifiedBy,createdOn,ModifiedOn) VALUES('119100','Kankavli','','119','1','1',now(),now());
INSERT INTO com_code(codeID, codeNameEn,codeNameMr,codeGroupID,createdBy,modifiedBy,createdOn,ModifiedOn) VALUES('119101','Vaibhavwadi','','119','1','1',now(),now());
INSERT INTO com_code(codeID, codeNameEn,codeNameMr,codeGroupID,createdBy,modifiedBy,createdOn,ModifiedOn) VALUES('119102','Devgad','','119','1','1',now(),now());
INSERT INTO com_code(codeID, codeNameEn,codeNameMr,codeGroupID,createdBy,modifiedBy,createdOn,ModifiedOn) VALUES('119103','Malwan','','119','1','1',now(),now());
INSERT INTO com_code(codeID, codeNameEn,codeNameMr,codeGroupID,createdBy,modifiedBy,createdOn,ModifiedOn) VALUES('119104','Sawantwadi','','119','1','1',now(),now());
INSERT INTO com_code(codeID, codeNameEn,codeNameMr,codeGroupID,createdBy,modifiedBy,createdOn,ModifiedOn) VALUES('119105','Kudal','','119','1','1',now(),now());
INSERT INTO com_code(codeID, codeNameEn,codeNameMr,codeGroupID,createdBy,modifiedBy,createdOn,ModifiedOn) VALUES('119106','Vengurla','','119','1','1',now(),now());
INSERT INTO com_code(codeID, codeNameEn,codeNameMr,codeGroupID,createdBy,modifiedBy,createdOn,ModifiedOn) VALUES('119107','Dodamarg (Kasai)','','119','1','1',now(),now());
INSERT INTO com_code(codeID, codeNameEn,codeNameMr,codeGroupID,createdBy,modifiedBy,createdOn,ModifiedOn) VALUES('119108','Ratnagiri','','119','1','1',now(),now());
INSERT INTO com_code(codeID, codeNameEn,codeNameMr,codeGroupID,createdBy,modifiedBy,createdOn,ModifiedOn) VALUES('119109','Sangameshwar (Deorukh)','','119','1','1',now(),now());
INSERT INTO com_code(codeID, codeNameEn,codeNameMr,codeGroupID,createdBy,modifiedBy,createdOn,ModifiedOn) VALUES('119110','Lanja','','119','1','1',now(),now());
INSERT INTO com_code(codeID, codeNameEn,codeNameMr,codeGroupID,createdBy,modifiedBy,createdOn,ModifiedOn) VALUES('119111','Rajapur','','119','1','1',now(),now());
INSERT INTO com_code(codeID, codeNameEn,codeNameMr,codeGroupID,createdBy,modifiedBy,createdOn,ModifiedOn) VALUES('119112','Chiplun','','119','1','1',now(),now());
INSERT INTO com_code(codeID, codeNameEn,codeNameMr,codeGroupID,createdBy,modifiedBy,createdOn,ModifiedOn) VALUES('119113','Guhagar','','119','1','1',now(),now());
INSERT INTO com_code(codeID, codeNameEn,codeNameMr,codeGroupID,createdBy,modifiedBy,createdOn,ModifiedOn) VALUES('119114','Dapoli','','119','1','1',now(),now());
INSERT INTO com_code(codeID, codeNameEn,codeNameMr,codeGroupID,createdBy,modifiedBy,createdOn,ModifiedOn) VALUES('119115','Mandangad','','119','1','1',now(),now());
INSERT INTO com_code(codeID, codeNameEn,codeNameMr,codeGroupID,createdBy,modifiedBy,createdOn,ModifiedOn) VALUES('119116','Khed','','119','1','1',now(),now());
INSERT INTO com_code(codeID, codeNameEn,codeNameMr,codeGroupID,createdBy,modifiedBy,createdOn,ModifiedOn) VALUES('119117','Pen','','119','1','1',now(),now());
INSERT INTO com_code(codeID, codeNameEn,codeNameMr,codeGroupID,createdBy,modifiedBy,createdOn,ModifiedOn) VALUES('119118','Alibaug','','119','1','1',now(),now());
INSERT INTO com_code(codeID, codeNameEn,codeNameMr,codeGroupID,createdBy,modifiedBy,createdOn,ModifiedOn) VALUES('119119','Murud','','119','1','1',now(),now());
INSERT INTO com_code(codeID, codeNameEn,codeNameMr,codeGroupID,createdBy,modifiedBy,createdOn,ModifiedOn) VALUES('119120','Panvel','','119','1','1',now(),now());
INSERT INTO com_code(codeID, codeNameEn,codeNameMr,codeGroupID,createdBy,modifiedBy,createdOn,ModifiedOn) VALUES('119121','Uran','','119','1','1',now(),now());
INSERT INTO com_code(codeID, codeNameEn,codeNameMr,codeGroupID,createdBy,modifiedBy,createdOn,ModifiedOn) VALUES('119122','Karjat (Matheran)','','119','1','1',now(),now());
INSERT INTO com_code(codeID, codeNameEn,codeNameMr,codeGroupID,createdBy,modifiedBy,createdOn,ModifiedOn) VALUES('119123','Khalapur','','119','1','1',now(),now());
INSERT INTO com_code(codeID, codeNameEn,codeNameMr,codeGroupID,createdBy,modifiedBy,createdOn,ModifiedOn) VALUES('119124','Mangaon','','119','1','1',now(),now());
INSERT INTO com_code(codeID, codeNameEn,codeNameMr,codeGroupID,createdBy,modifiedBy,createdOn,ModifiedOn) VALUES('119125','Tala','','119','1','1',now(),now());
INSERT INTO com_code(codeID, codeNameEn,codeNameMr,codeGroupID,createdBy,modifiedBy,createdOn,ModifiedOn) VALUES('119126','Roha','','119','1','1',now(),now());
INSERT INTO com_code(codeID, codeNameEn,codeNameMr,codeGroupID,createdBy,modifiedBy,createdOn,ModifiedOn) VALUES('119127','Sudhagad (Pali)','','119','1','1',now(),now());
INSERT INTO com_code(codeID, codeNameEn,codeNameMr,codeGroupID,createdBy,modifiedBy,createdOn,ModifiedOn) VALUES('119128','Mahad','','119','1','1',now(),now());
INSERT INTO com_code(codeID, codeNameEn,codeNameMr,codeGroupID,createdBy,modifiedBy,createdOn,ModifiedOn) VALUES('119129','Poladpur','','119','1','1',now(),now());
INSERT INTO com_code(codeID, codeNameEn,codeNameMr,codeGroupID,createdBy,modifiedBy,createdOn,ModifiedOn) VALUES('119130','Shrivardhan','','119','1','1',now(),now());
INSERT INTO com_code(codeID, codeNameEn,codeNameMr,codeGroupID,createdBy,modifiedBy,createdOn,ModifiedOn) VALUES('119131','Mhasla','','119','1','1',now(),now());
INSERT INTO com_code(codeID, codeNameEn,codeNameMr,codeGroupID,createdBy,modifiedBy,createdOn,ModifiedOn) VALUES('119132','Kurla (Mulund)','','119','1','1',now(),now());
INSERT INTO com_code(codeID, codeNameEn,codeNameMr,codeGroupID,createdBy,modifiedBy,createdOn,ModifiedOn) VALUES('119133','Andheri','','119','1','1',now(),now());
INSERT INTO com_code(codeID, codeNameEn,codeNameMr,codeGroupID,createdBy,modifiedBy,createdOn,ModifiedOn) VALUES('119134','Borivali','','119','1','1',now(),now());
INSERT INTO com_code(codeID, codeNameEn,codeNameMr,codeGroupID,createdBy,modifiedBy,createdOn,ModifiedOn) VALUES('119135','Thane','','119','1','1',now(),now());
INSERT INTO com_code(codeID, codeNameEn,codeNameMr,codeGroupID,createdBy,modifiedBy,createdOn,ModifiedOn) VALUES('119136','Kalyan','','119','1','1',now(),now());
INSERT INTO com_code(codeID, codeNameEn,codeNameMr,codeGroupID,createdBy,modifiedBy,createdOn,ModifiedOn) VALUES('119137','Murbad','','119','1','1',now(),now());
INSERT INTO com_code(codeID, codeNameEn,codeNameMr,codeGroupID,createdBy,modifiedBy,createdOn,ModifiedOn) VALUES('119138','Bhiwandi','','119','1','1',now(),now());
INSERT INTO com_code(codeID, codeNameEn,codeNameMr,codeGroupID,createdBy,modifiedBy,createdOn,ModifiedOn) VALUES('119139','Shahapur','','119','1','1',now(),now());
INSERT INTO com_code(codeID, codeNameEn,codeNameMr,codeGroupID,createdBy,modifiedBy,createdOn,ModifiedOn) VALUES('119140','Ulhasnagar','','119','1','1',now(),now());
INSERT INTO com_code(codeID, codeNameEn,codeNameMr,codeGroupID,createdBy,modifiedBy,createdOn,ModifiedOn) VALUES('119141','Ambarnath','','119','1','1',now(),now());
INSERT INTO com_code(codeID, codeNameEn,codeNameMr,codeGroupID,createdBy,modifiedBy,createdOn,ModifiedOn) VALUES('119142','Palghar','','119','1','1',now(),now());
INSERT INTO com_code(codeID, codeNameEn,codeNameMr,codeGroupID,createdBy,modifiedBy,createdOn,ModifiedOn) VALUES('119143','Vasai','','119','1','1',now(),now());
INSERT INTO com_code(codeID, codeNameEn,codeNameMr,codeGroupID,createdBy,modifiedBy,createdOn,ModifiedOn) VALUES('119144','Dahanu','','119','1','1',now(),now());
INSERT INTO com_code(codeID, codeNameEn,codeNameMr,codeGroupID,createdBy,modifiedBy,createdOn,ModifiedOn) VALUES('119145','Talasari','','119','1','1',now(),now());
INSERT INTO com_code(codeID, codeNameEn,codeNameMr,codeGroupID,createdBy,modifiedBy,createdOn,ModifiedOn) VALUES('119146','Jawhar','','119','1','1',now(),now());
INSERT INTO com_code(codeID, codeNameEn,codeNameMr,codeGroupID,createdBy,modifiedBy,createdOn,ModifiedOn) VALUES('119147','Mokhada','','119','1','1',now(),now());
INSERT INTO com_code(codeID, codeNameEn,codeNameMr,codeGroupID,createdBy,modifiedBy,createdOn,ModifiedOn) VALUES('119148','Vada','','119','1','1',now(),now());
INSERT INTO com_code(codeID, codeNameEn,codeNameMr,codeGroupID,createdBy,modifiedBy,createdOn,ModifiedOn) VALUES('119149','Vikramgad','','119','1','1',now(),now());
INSERT INTO com_code(codeID, codeNameEn,codeNameMr,codeGroupID,createdBy,modifiedBy,createdOn,ModifiedOn) VALUES('119150','Nashik','','119','1','1',now(),now());
INSERT INTO com_code(codeID, codeNameEn,codeNameMr,codeGroupID,createdBy,modifiedBy,createdOn,ModifiedOn) VALUES('119151','Igatpuri','','119','1','1',now(),now());
INSERT INTO com_code(codeID, codeNameEn,codeNameMr,codeGroupID,createdBy,modifiedBy,createdOn,ModifiedOn) VALUES('119152','Dindori','','119','1','1',now(),now());
INSERT INTO com_code(codeID, codeNameEn,codeNameMr,codeGroupID,createdBy,modifiedBy,createdOn,ModifiedOn) VALUES('119153','Peth','','119','1','1',now(),now());
INSERT INTO com_code(codeID, codeNameEn,codeNameMr,codeGroupID,createdBy,modifiedBy,createdOn,ModifiedOn) VALUES('119154','Trimbakeshwar','','119','1','1',now(),now());
INSERT INTO com_code(codeID, codeNameEn,codeNameMr,codeGroupID,createdBy,modifiedBy,createdOn,ModifiedOn) VALUES('119155','Kalwan','','119','1','1',now(),now());
INSERT INTO com_code(codeID, codeNameEn,codeNameMr,codeGroupID,createdBy,modifiedBy,createdOn,ModifiedOn) VALUES('119156','Deola','','119','1','1',now(),now());
INSERT INTO com_code(codeID, codeNameEn,codeNameMr,codeGroupID,createdBy,modifiedBy,createdOn,ModifiedOn) VALUES('119157','Surgana','','119','1','1',now(),now());
INSERT INTO com_code(codeID, codeNameEn,codeNameMr,codeGroupID,createdBy,modifiedBy,createdOn,ModifiedOn) VALUES('119158','Baglan (Satana)','','119','1','1',now(),now());
INSERT INTO com_code(codeID, codeNameEn,codeNameMr,codeGroupID,createdBy,modifiedBy,createdOn,ModifiedOn) VALUES('119159','Malegaon','','119','1','1',now(),now());
INSERT INTO com_code(codeID, codeNameEn,codeNameMr,codeGroupID,createdBy,modifiedBy,createdOn,ModifiedOn) VALUES('119160','Nandgaon','','119','1','1',now(),now());
INSERT INTO com_code(codeID, codeNameEn,codeNameMr,codeGroupID,createdBy,modifiedBy,createdOn,ModifiedOn) VALUES('119161','Chandwad','','119','1','1',now(),now());
INSERT INTO com_code(codeID, codeNameEn,codeNameMr,codeGroupID,createdBy,modifiedBy,createdOn,ModifiedOn) VALUES('119162','Niphad','','119','1','1',now(),now());
INSERT INTO com_code(codeID, codeNameEn,codeNameMr,codeGroupID,createdBy,modifiedBy,createdOn,ModifiedOn) VALUES('119163','Sinnar','','119','1','1',now(),now());
INSERT INTO com_code(codeID, codeNameEn,codeNameMr,codeGroupID,createdBy,modifiedBy,createdOn,ModifiedOn) VALUES('119164','Yeola','','119','1','1',now(),now());
INSERT INTO com_code(codeID, codeNameEn,codeNameMr,codeGroupID,createdBy,modifiedBy,createdOn,ModifiedOn) VALUES('119165','Nandurbar','','119','1','1',now(),now());
INSERT INTO com_code(codeID, codeNameEn,codeNameMr,codeGroupID,createdBy,modifiedBy,createdOn,ModifiedOn) VALUES('119166','Navapur','','119','1','1',now(),now());
INSERT INTO com_code(codeID, codeNameEn,codeNameMr,codeGroupID,createdBy,modifiedBy,createdOn,ModifiedOn) VALUES('119167','Shahada','','119','1','1',now(),now());
INSERT INTO com_code(codeID, codeNameEn,codeNameMr,codeGroupID,createdBy,modifiedBy,createdOn,ModifiedOn) VALUES('119168','Talode','','119','1','1',now(),now());
INSERT INTO com_code(codeID, codeNameEn,codeNameMr,codeGroupID,createdBy,modifiedBy,createdOn,ModifiedOn) VALUES('119169','Akkalkuwa','','119','1','1',now(),now());
INSERT INTO com_code(codeID, codeNameEn,codeNameMr,codeGroupID,createdBy,modifiedBy,createdOn,ModifiedOn) VALUES('119170','Akrani (Dhadgaon)','','119','1','1',now(),now());
INSERT INTO com_code(codeID, codeNameEn,codeNameMr,codeGroupID,createdBy,modifiedBy,createdOn,ModifiedOn) VALUES('119171','Dhule','','119','1','1',now(),now());
INSERT INTO com_code(codeID, codeNameEn,codeNameMr,codeGroupID,createdBy,modifiedBy,createdOn,ModifiedOn) VALUES('119172','Sakri','','119','1','1',now(),now());
INSERT INTO com_code(codeID, codeNameEn,codeNameMr,codeGroupID,createdBy,modifiedBy,createdOn,ModifiedOn) VALUES('119173','Sindkheda','','119','1','1',now(),now());
INSERT INTO com_code(codeID, codeNameEn,codeNameMr,codeGroupID,createdBy,modifiedBy,createdOn,ModifiedOn) VALUES('119174','Shirpur','','119','1','1',now(),now());
INSERT INTO com_code(codeID, codeNameEn,codeNameMr,codeGroupID,createdBy,modifiedBy,createdOn,ModifiedOn) VALUES('119175','Jalgaon','','119','1','1',now(),now());
INSERT INTO com_code(codeID, codeNameEn,codeNameMr,codeGroupID,createdBy,modifiedBy,createdOn,ModifiedOn) VALUES('119176','Jamner','','119','1','1',now(),now());
INSERT INTO com_code(codeID, codeNameEn,codeNameMr,codeGroupID,createdBy,modifiedBy,createdOn,ModifiedOn) VALUES('119177','Erandol','','119','1','1',now(),now());
INSERT INTO com_code(codeID, codeNameEn,codeNameMr,codeGroupID,createdBy,modifiedBy,createdOn,ModifiedOn) VALUES('119178','Dharangaon','','119','1','1',now(),now());
INSERT INTO com_code(codeID, codeNameEn,codeNameMr,codeGroupID,createdBy,modifiedBy,createdOn,ModifiedOn) VALUES('119179','Bhusawal','','119','1','1',now(),now());
INSERT INTO com_code(codeID, codeNameEn,codeNameMr,codeGroupID,createdBy,modifiedBy,createdOn,ModifiedOn) VALUES('119180','Raver','','119','1','1',now(),now());
INSERT INTO com_code(codeID, codeNameEn,codeNameMr,codeGroupID,createdBy,modifiedBy,createdOn,ModifiedOn) VALUES('119181','Muktainagar (Edalabad)','','119','1','1',now(),now());
INSERT INTO com_code(codeID, codeNameEn,codeNameMr,codeGroupID,createdBy,modifiedBy,createdOn,ModifiedOn) VALUES('119182','Bodwad','','119','1','1',now(),now());
INSERT INTO com_code(codeID, codeNameEn,codeNameMr,codeGroupID,createdBy,modifiedBy,createdOn,ModifiedOn) VALUES('119183','Yawal','','119','1','1',now(),now());
INSERT INTO com_code(codeID, codeNameEn,codeNameMr,codeGroupID,createdBy,modifiedBy,createdOn,ModifiedOn) VALUES('119184','Amalner','','119','1','1',now(),now());
INSERT INTO com_code(codeID, codeNameEn,codeNameMr,codeGroupID,createdBy,modifiedBy,createdOn,ModifiedOn) VALUES('119185','Parola','','119','1','1',now(),now());
INSERT INTO com_code(codeID, codeNameEn,codeNameMr,codeGroupID,createdBy,modifiedBy,createdOn,ModifiedOn) VALUES('119186','Chopda','','119','1','1',now(),now());
INSERT INTO com_code(codeID, codeNameEn,codeNameMr,codeGroupID,createdBy,modifiedBy,createdOn,ModifiedOn) VALUES('119187','Pachora','','119','1','1',now(),now());
INSERT INTO com_code(codeID, codeNameEn,codeNameMr,codeGroupID,createdBy,modifiedBy,createdOn,ModifiedOn) VALUES('119188','Bhadgaon','','119','1','1',now(),now());
INSERT INTO com_code(codeID, codeNameEn,codeNameMr,codeGroupID,createdBy,modifiedBy,createdOn,ModifiedOn) VALUES('119189','Chalisgaon','','119','1','1',now(),now());
INSERT INTO com_code(codeID, codeNameEn,codeNameMr,codeGroupID,createdBy,modifiedBy,createdOn,ModifiedOn) VALUES('119190','Buldhana','','119','1','1',now(),now());
INSERT INTO com_code(codeID, codeNameEn,codeNameMr,codeGroupID,createdBy,modifiedBy,createdOn,ModifiedOn) VALUES('119191','Chikhli','','119','1','1',now(),now());
INSERT INTO com_code(codeID, codeNameEn,codeNameMr,codeGroupID,createdBy,modifiedBy,createdOn,ModifiedOn) VALUES('119192','Deulgaon Raja','','119','1','1',now(),now());
INSERT INTO com_code(codeID, codeNameEn,codeNameMr,codeGroupID,createdBy,modifiedBy,createdOn,ModifiedOn) VALUES('119193','Jalgaon Jamod','','119','1','1',now(),now());
INSERT INTO com_code(codeID, codeNameEn,codeNameMr,codeGroupID,createdBy,modifiedBy,createdOn,ModifiedOn) VALUES('119194','Sangrampur','','119','1','1',now(),now());
INSERT INTO com_code(codeID, codeNameEn,codeNameMr,codeGroupID,createdBy,modifiedBy,createdOn,ModifiedOn) VALUES('119195','Malkapur','','119','1','1',now(),now());
INSERT INTO com_code(codeID, codeNameEn,codeNameMr,codeGroupID,createdBy,modifiedBy,createdOn,ModifiedOn) VALUES('119196','Motala','','119','1','1',now(),now());
INSERT INTO com_code(codeID, codeNameEn,codeNameMr,codeGroupID,createdBy,modifiedBy,createdOn,ModifiedOn) VALUES('119197','Nandura','','119','1','1',now(),now());
INSERT INTO com_code(codeID, codeNameEn,codeNameMr,codeGroupID,createdBy,modifiedBy,createdOn,ModifiedOn) VALUES('119198','Khamgaon','','119','1','1',now(),now());
INSERT INTO com_code(codeID, codeNameEn,codeNameMr,codeGroupID,createdBy,modifiedBy,createdOn,ModifiedOn) VALUES('119199','Shegaon','','119','1','1',now(),now());
INSERT INTO com_code(codeID, codeNameEn,codeNameMr,codeGroupID,createdBy,modifiedBy,createdOn,ModifiedOn) VALUES('119200','Mehkar','','119','1','1',now(),now());
INSERT INTO com_code(codeID, codeNameEn,codeNameMr,codeGroupID,createdBy,modifiedBy,createdOn,ModifiedOn) VALUES('119201','Sindkhed Raja','','119','1','1',now(),now());
INSERT INTO com_code(codeID, codeNameEn,codeNameMr,codeGroupID,createdBy,modifiedBy,createdOn,ModifiedOn) VALUES('119202','Lonar','','119','1','1',now(),now());
INSERT INTO com_code(codeID, codeNameEn,codeNameMr,codeGroupID,createdBy,modifiedBy,createdOn,ModifiedOn) VALUES('119203','Akola','','119','1','1',now(),now());
INSERT INTO com_code(codeID, codeNameEn,codeNameMr,codeGroupID,createdBy,modifiedBy,createdOn,ModifiedOn) VALUES('119204','Akot','','119','1','1',now(),now());
INSERT INTO com_code(codeID, codeNameEn,codeNameMr,codeGroupID,createdBy,modifiedBy,createdOn,ModifiedOn) VALUES('119205','Telhara','','119','1','1',now(),now());
INSERT INTO com_code(codeID, codeNameEn,codeNameMr,codeGroupID,createdBy,modifiedBy,createdOn,ModifiedOn) VALUES('119206','Balapur','','119','1','1',now(),now());
INSERT INTO com_code(codeID, codeNameEn,codeNameMr,codeGroupID,createdBy,modifiedBy,createdOn,ModifiedOn) VALUES('119207','Patur','','119','1','1',now(),now());
INSERT INTO com_code(codeID, codeNameEn,codeNameMr,codeGroupID,createdBy,modifiedBy,createdOn,ModifiedOn) VALUES('119208','Murtajapur','','119','1','1',now(),now());
INSERT INTO com_code(codeID, codeNameEn,codeNameMr,codeGroupID,createdBy,modifiedBy,createdOn,ModifiedOn) VALUES('119209','Barshitakli','','119','1','1',now(),now());
INSERT INTO com_code(codeID, codeNameEn,codeNameMr,codeGroupID,createdBy,modifiedBy,createdOn,ModifiedOn) VALUES('119210','Washim','','119','1','1',now(),now());
INSERT INTO com_code(codeID, codeNameEn,codeNameMr,codeGroupID,createdBy,modifiedBy,createdOn,ModifiedOn) VALUES('119211','Malegaon','','119','1','1',now(),now());
INSERT INTO com_code(codeID, codeNameEn,codeNameMr,codeGroupID,createdBy,modifiedBy,createdOn,ModifiedOn) VALUES('119212','Risod','','119','1','1',now(),now());
INSERT INTO com_code(codeID, codeNameEn,codeNameMr,codeGroupID,createdBy,modifiedBy,createdOn,ModifiedOn) VALUES('119213','Mangrulpir','','119','1','1',now(),now());
INSERT INTO com_code(codeID, codeNameEn,codeNameMr,codeGroupID,createdBy,modifiedBy,createdOn,ModifiedOn) VALUES('119214','Karanja','','119','1','1',now(),now());
INSERT INTO com_code(codeID, codeNameEn,codeNameMr,codeGroupID,createdBy,modifiedBy,createdOn,ModifiedOn) VALUES('119215','Manora','','119','1','1',now(),now());
INSERT INTO com_code(codeID, codeNameEn,codeNameMr,codeGroupID,createdBy,modifiedBy,createdOn,ModifiedOn) VALUES('119216','Amravati','','119','1','1',now(),now());
INSERT INTO com_code(codeID, codeNameEn,codeNameMr,codeGroupID,createdBy,modifiedBy,createdOn,ModifiedOn) VALUES('119217','Bhatukali','','119','1','1',now(),now());
INSERT INTO com_code(codeID, codeNameEn,codeNameMr,codeGroupID,createdBy,modifiedBy,createdOn,ModifiedOn) VALUES('119218','Nandgaon Khandeshwar','','119','1','1',now(),now());
INSERT INTO com_code(codeID, codeNameEn,codeNameMr,codeGroupID,createdBy,modifiedBy,createdOn,ModifiedOn) VALUES('119219','Dharni (Amravati)','','119','1','1',now(),now());
INSERT INTO com_code(codeID, codeNameEn,codeNameMr,codeGroupID,createdBy,modifiedBy,createdOn,ModifiedOn) VALUES('119220','Chikhaldara','','119','1','1',now(),now());
INSERT INTO com_code(codeID, codeNameEn,codeNameMr,codeGroupID,createdBy,modifiedBy,createdOn,ModifiedOn) VALUES('119221','Achalpur','','119','1','1',now(),now());
INSERT INTO com_code(codeID, codeNameEn,codeNameMr,codeGroupID,createdBy,modifiedBy,createdOn,ModifiedOn) VALUES('119222','Chandurbazar','','119','1','1',now(),now());
INSERT INTO com_code(codeID, codeNameEn,codeNameMr,codeGroupID,createdBy,modifiedBy,createdOn,ModifiedOn) VALUES('119223','Morshi','','119','1','1',now(),now());
INSERT INTO com_code(codeID, codeNameEn,codeNameMr,codeGroupID,createdBy,modifiedBy,createdOn,ModifiedOn) VALUES('119224','Warud','','119','1','1',now(),now());
INSERT INTO com_code(codeID, codeNameEn,codeNameMr,codeGroupID,createdBy,modifiedBy,createdOn,ModifiedOn) VALUES('119225','Daryapur','','119','1','1',now(),now());
INSERT INTO com_code(codeID, codeNameEn,codeNameMr,codeGroupID,createdBy,modifiedBy,createdOn,ModifiedOn) VALUES('119226','Anjangaon-Surji','','119','1','1',now(),now());
INSERT INTO com_code(codeID, codeNameEn,codeNameMr,codeGroupID,createdBy,modifiedBy,createdOn,ModifiedOn) VALUES('119227','Chandur','','119','1','1',now(),now());
INSERT INTO com_code(codeID, codeNameEn,codeNameMr,codeGroupID,createdBy,modifiedBy,createdOn,ModifiedOn) VALUES('119228','Dhamangaon','','119','1','1',now(),now());
INSERT INTO com_code(codeID, codeNameEn,codeNameMr,codeGroupID,createdBy,modifiedBy,createdOn,ModifiedOn) VALUES('119229','Tiosa','','119','1','1',now(),now());
INSERT INTO com_code(codeID, codeNameEn,codeNameMr,codeGroupID,createdBy,modifiedBy,createdOn,ModifiedOn) VALUES('119230','Wardha','','119','1','1',now(),now());
INSERT INTO com_code(codeID, codeNameEn,codeNameMr,codeGroupID,createdBy,modifiedBy,createdOn,ModifiedOn) VALUES('119231','Deoli','','119','1','1',now(),now());
INSERT INTO com_code(codeID, codeNameEn,codeNameMr,codeGroupID,createdBy,modifiedBy,createdOn,ModifiedOn) VALUES('119232','Seloo','','119','1','1',now(),now());
INSERT INTO com_code(codeID, codeNameEn,codeNameMr,codeGroupID,createdBy,modifiedBy,createdOn,ModifiedOn) VALUES('119233','Arvi','','119','1','1',now(),now());
INSERT INTO com_code(codeID, codeNameEn,codeNameMr,codeGroupID,createdBy,modifiedBy,createdOn,ModifiedOn) VALUES('119234','Ashti','','119','1','1',now(),now());
INSERT INTO com_code(codeID, codeNameEn,codeNameMr,codeGroupID,createdBy,modifiedBy,createdOn,ModifiedOn) VALUES('119235','Karanja','','119','1','1',now(),now());
INSERT INTO com_code(codeID, codeNameEn,codeNameMr,codeGroupID,createdBy,modifiedBy,createdOn,ModifiedOn) VALUES('119236','Hinganghat','','119','1','1',now(),now());
INSERT INTO com_code(codeID, codeNameEn,codeNameMr,codeGroupID,createdBy,modifiedBy,createdOn,ModifiedOn) VALUES('119237','Samudrapur','','119','1','1',now(),now());
INSERT INTO com_code(codeID, codeNameEn,codeNameMr,codeGroupID,createdBy,modifiedBy,createdOn,ModifiedOn) VALUES('119238','Nagpur (Urban)','','119','1','1',now(),now());
INSERT INTO com_code(codeID, codeNameEn,codeNameMr,codeGroupID,createdBy,modifiedBy,createdOn,ModifiedOn) VALUES('119239','Nagpur (Rural)','','119','1','1',now(),now());
INSERT INTO com_code(codeID, codeNameEn,codeNameMr,codeGroupID,createdBy,modifiedBy,createdOn,ModifiedOn) VALUES('119240','Kamptee','','119','1','1',now(),now());
INSERT INTO com_code(codeID, codeNameEn,codeNameMr,codeGroupID,createdBy,modifiedBy,createdOn,ModifiedOn) VALUES('119241','Hingna','','119','1','1',now(),now());
INSERT INTO com_code(codeID, codeNameEn,codeNameMr,codeGroupID,createdBy,modifiedBy,createdOn,ModifiedOn) VALUES('119242','Katol','','119','1','1',now(),now());
INSERT INTO com_code(codeID, codeNameEn,codeNameMr,codeGroupID,createdBy,modifiedBy,createdOn,ModifiedOn) VALUES('119243','Narkhed','','119','1','1',now(),now());
INSERT INTO com_code(codeID, codeNameEn,codeNameMr,codeGroupID,createdBy,modifiedBy,createdOn,ModifiedOn) VALUES('119244','Savner','','119','1','1',now(),now());
INSERT INTO com_code(codeID, codeNameEn,codeNameMr,codeGroupID,createdBy,modifiedBy,createdOn,ModifiedOn) VALUES('119245','Kalameshwar','','119','1','1',now(),now());
INSERT INTO com_code(codeID, codeNameEn,codeNameMr,codeGroupID,createdBy,modifiedBy,createdOn,ModifiedOn) VALUES('119246','Ramtek','','119','1','1',now(),now());
INSERT INTO com_code(codeID, codeNameEn,codeNameMr,codeGroupID,createdBy,modifiedBy,createdOn,ModifiedOn) VALUES('119247','Mouda','','119','1','1',now(),now());
INSERT INTO com_code(codeID, codeNameEn,codeNameMr,codeGroupID,createdBy,modifiedBy,createdOn,ModifiedOn) VALUES('119248','Parseoni','','119','1','1',now(),now());
INSERT INTO com_code(codeID, codeNameEn,codeNameMr,codeGroupID,createdBy,modifiedBy,createdOn,ModifiedOn) VALUES('119249','Umred','','119','1','1',now(),now());
INSERT INTO com_code(codeID, codeNameEn,codeNameMr,codeGroupID,createdBy,modifiedBy,createdOn,ModifiedOn) VALUES('119250','Kuhi','','119','1','1',now(),now());
INSERT INTO com_code(codeID, codeNameEn,codeNameMr,codeGroupID,createdBy,modifiedBy,createdOn,ModifiedOn) VALUES('119251','Bhiwapur','','119','1','1',now(),now());
INSERT INTO com_code(codeID, codeNameEn,codeNameMr,codeGroupID,createdBy,modifiedBy,createdOn,ModifiedOn) VALUES('119252','Bhandara','','119','1','1',now(),now());
INSERT INTO com_code(codeID, codeNameEn,codeNameMr,codeGroupID,createdBy,modifiedBy,createdOn,ModifiedOn) VALUES('119253','Tumsar','','119','1','1',now(),now());
INSERT INTO com_code(codeID, codeNameEn,codeNameMr,codeGroupID,createdBy,modifiedBy,createdOn,ModifiedOn) VALUES('119254','Pauni','','119','1','1',now(),now());
INSERT INTO com_code(codeID, codeNameEn,codeNameMr,codeGroupID,createdBy,modifiedBy,createdOn,ModifiedOn) VALUES('119255','Mohadi','','119','1','1',now(),now());
INSERT INTO com_code(codeID, codeNameEn,codeNameMr,codeGroupID,createdBy,modifiedBy,createdOn,ModifiedOn) VALUES('119256','Sakoli','','119','1','1',now(),now());
INSERT INTO com_code(codeID, codeNameEn,codeNameMr,codeGroupID,createdBy,modifiedBy,createdOn,ModifiedOn) VALUES('119257','Lakhni','','119','1','1',now(),now());
INSERT INTO com_code(codeID, codeNameEn,codeNameMr,codeGroupID,createdBy,modifiedBy,createdOn,ModifiedOn) VALUES('119258','Lakhandur','','119','1','1',now(),now());
INSERT INTO com_code(codeID, codeNameEn,codeNameMr,codeGroupID,createdBy,modifiedBy,createdOn,ModifiedOn) VALUES('119259','Gondia','','119','1','1',now(),now());
INSERT INTO com_code(codeID, codeNameEn,codeNameMr,codeGroupID,createdBy,modifiedBy,createdOn,ModifiedOn) VALUES('119260','Tirora','','119','1','1',now(),now());
INSERT INTO com_code(codeID, codeNameEn,codeNameMr,codeGroupID,createdBy,modifiedBy,createdOn,ModifiedOn) VALUES('119261','Goregaon','','119','1','1',now(),now());
INSERT INTO com_code(codeID, codeNameEn,codeNameMr,codeGroupID,createdBy,modifiedBy,createdOn,ModifiedOn) VALUES('119262','Arjuni Morgaon','','119','1','1',now(),now());
INSERT INTO com_code(codeID, codeNameEn,codeNameMr,codeGroupID,createdBy,modifiedBy,createdOn,ModifiedOn) VALUES('119263','Amgaon','','119','1','1',now(),now());
INSERT INTO com_code(codeID, codeNameEn,codeNameMr,codeGroupID,createdBy,modifiedBy,createdOn,ModifiedOn) VALUES('119264','Salekasa','','119','1','1',now(),now());
INSERT INTO com_code(codeID, codeNameEn,codeNameMr,codeGroupID,createdBy,modifiedBy,createdOn,ModifiedOn) VALUES('119265','Sadak Arjuni','','119','1','1',now(),now());
INSERT INTO com_code(codeID, codeNameEn,codeNameMr,codeGroupID,createdBy,modifiedBy,createdOn,ModifiedOn) VALUES('119266','Deori','','119','1','1',now(),now());
INSERT INTO com_code(codeID, codeNameEn,codeNameMr,codeGroupID,createdBy,modifiedBy,createdOn,ModifiedOn) VALUES('119267','Gadchiroli','','119','1','1',now(),now());
INSERT INTO com_code(codeID, codeNameEn,codeNameMr,codeGroupID,createdBy,modifiedBy,createdOn,ModifiedOn) VALUES('119268','Dhanora','','119','1','1',now(),now());
INSERT INTO com_code(codeID, codeNameEn,codeNameMr,codeGroupID,createdBy,modifiedBy,createdOn,ModifiedOn) VALUES('119269','Chamorshi','','119','1','1',now(),now());
INSERT INTO com_code(codeID, codeNameEn,codeNameMr,codeGroupID,createdBy,modifiedBy,createdOn,ModifiedOn) VALUES('119270','Mulchera','','119','1','1',now(),now());
INSERT INTO com_code(codeID, codeNameEn,codeNameMr,codeGroupID,createdBy,modifiedBy,createdOn,ModifiedOn) VALUES('119271','Desaiganj (Vadasa)','','119','1','1',now(),now());
INSERT INTO com_code(codeID, codeNameEn,codeNameMr,codeGroupID,createdBy,modifiedBy,createdOn,ModifiedOn) VALUES('119272','Armori','','119','1','1',now(),now());
INSERT INTO com_code(codeID, codeNameEn,codeNameMr,codeGroupID,createdBy,modifiedBy,createdOn,ModifiedOn) VALUES('119273','Kurkheda','','119','1','1',now(),now());
INSERT INTO com_code(codeID, codeNameEn,codeNameMr,codeGroupID,createdBy,modifiedBy,createdOn,ModifiedOn) VALUES('119274','Korchi','','119','1','1',now(),now());
INSERT INTO com_code(codeID, codeNameEn,codeNameMr,codeGroupID,createdBy,modifiedBy,createdOn,ModifiedOn) VALUES('119275','Aheri','','119','1','1',now(),now());
INSERT INTO com_code(codeID, codeNameEn,codeNameMr,codeGroupID,createdBy,modifiedBy,createdOn,ModifiedOn) VALUES('119276','Bhamragad','','119','1','1',now(),now());
INSERT INTO com_code(codeID, codeNameEn,codeNameMr,codeGroupID,createdBy,modifiedBy,createdOn,ModifiedOn) VALUES('119277','Sironcha','','119','1','1',now(),now());
INSERT INTO com_code(codeID, codeNameEn,codeNameMr,codeGroupID,createdBy,modifiedBy,createdOn,ModifiedOn) VALUES('119278','Chandrapur','','119','1','1',now(),now());
INSERT INTO com_code(codeID, codeNameEn,codeNameMr,codeGroupID,createdBy,modifiedBy,createdOn,ModifiedOn) VALUES('119279','Saoli','','119','1','1',now(),now());
INSERT INTO com_code(codeID, codeNameEn,codeNameMr,codeGroupID,createdBy,modifiedBy,createdOn,ModifiedOn) VALUES('119280','Mul','','119','1','1',now(),now());
INSERT INTO com_code(codeID, codeNameEn,codeNameMr,codeGroupID,createdBy,modifiedBy,createdOn,ModifiedOn) VALUES('119281','Ballarpur','','119','1','1',now(),now());
INSERT INTO com_code(codeID, codeNameEn,codeNameMr,codeGroupID,createdBy,modifiedBy,createdOn,ModifiedOn) VALUES('119282','Pombhurna','','119','1','1',now(),now());
INSERT INTO com_code(codeID, codeNameEn,codeNameMr,codeGroupID,createdBy,modifiedBy,createdOn,ModifiedOn) VALUES('119283','Gondpimpri','','119','1','1',now(),now());
INSERT INTO com_code(codeID, codeNameEn,codeNameMr,codeGroupID,createdBy,modifiedBy,createdOn,ModifiedOn) VALUES('119284','Warora','','119','1','1',now(),now());
INSERT INTO com_code(codeID, codeNameEn,codeNameMr,codeGroupID,createdBy,modifiedBy,createdOn,ModifiedOn) VALUES('119285','Chimur','','119','1','1',now(),now());
INSERT INTO com_code(codeID, codeNameEn,codeNameMr,codeGroupID,createdBy,modifiedBy,createdOn,ModifiedOn) VALUES('119286','Bhadravati','','119','1','1',now(),now());
INSERT INTO com_code(codeID, codeNameEn,codeNameMr,codeGroupID,createdBy,modifiedBy,createdOn,ModifiedOn) VALUES('119287','Bramhapuri','','119','1','1',now(),now());
INSERT INTO com_code(codeID, codeNameEn,codeNameMr,codeGroupID,createdBy,modifiedBy,createdOn,ModifiedOn) VALUES('119288','Nagbhid','','119','1','1',now(),now());
INSERT INTO com_code(codeID, codeNameEn,codeNameMr,codeGroupID,createdBy,modifiedBy,createdOn,ModifiedOn) VALUES('119289','Sindewahi','','119','1','1',now(),now());
INSERT INTO com_code(codeID, codeNameEn,codeNameMr,codeGroupID,createdBy,modifiedBy,createdOn,ModifiedOn) VALUES('119290','Rajura','','119','1','1',now(),now());
INSERT INTO com_code(codeID, codeNameEn,codeNameMr,codeGroupID,createdBy,modifiedBy,createdOn,ModifiedOn) VALUES('119291','Korpana','','119','1','1',now(),now());
INSERT INTO com_code(codeID, codeNameEn,codeNameMr,codeGroupID,createdBy,modifiedBy,createdOn,ModifiedOn) VALUES('119292','Jivati','','119','1','1',now(),now());
INSERT INTO com_code(codeID, codeNameEn,codeNameMr,codeGroupID,createdBy,modifiedBy,createdOn,ModifiedOn) VALUES('119293','Yavatmal','','119','1','1',now(),now());
INSERT INTO com_code(codeID, codeNameEn,codeNameMr,codeGroupID,createdBy,modifiedBy,createdOn,ModifiedOn) VALUES('119294','Arni','','119','1','1',now(),now());
INSERT INTO com_code(codeID, codeNameEn,codeNameMr,codeGroupID,createdBy,modifiedBy,createdOn,ModifiedOn) VALUES('119295','Babhulgaon','','119','1','1',now(),now());
INSERT INTO com_code(codeID, codeNameEn,codeNameMr,codeGroupID,createdBy,modifiedBy,createdOn,ModifiedOn) VALUES('119296','Kalamb','','119','1','1',now(),now());
INSERT INTO com_code(codeID, codeNameEn,codeNameMr,codeGroupID,createdBy,modifiedBy,createdOn,ModifiedOn) VALUES('119297','Darwha','','119','1','1',now(),now());
INSERT INTO com_code(codeID, codeNameEn,codeNameMr,codeGroupID,createdBy,modifiedBy,createdOn,ModifiedOn) VALUES('119298','Digras','','119','1','1',now(),now());
INSERT INTO com_code(codeID, codeNameEn,codeNameMr,codeGroupID,createdBy,modifiedBy,createdOn,ModifiedOn) VALUES('119299','Ner','','119','1','1',now(),now());
INSERT INTO com_code(codeID, codeNameEn,codeNameMr,codeGroupID,createdBy,modifiedBy,createdOn,ModifiedOn) VALUES('119300','Pusad','','119','1','1',now(),now());
INSERT INTO com_code(codeID, codeNameEn,codeNameMr,codeGroupID,createdBy,modifiedBy,createdOn,ModifiedOn) VALUES('119301','Umarkhed','','119','1','1',now(),now());
INSERT INTO com_code(codeID, codeNameEn,codeNameMr,codeGroupID,createdBy,modifiedBy,createdOn,ModifiedOn) VALUES('119302','Mahagaon','','119','1','1',now(),now());
INSERT INTO com_code(codeID, codeNameEn,codeNameMr,codeGroupID,createdBy,modifiedBy,createdOn,ModifiedOn) VALUES('119303','Kelapur (Pandharkawada)','','119','1','1',now(),now());
INSERT INTO com_code(codeID, codeNameEn,codeNameMr,codeGroupID,createdBy,modifiedBy,createdOn,ModifiedOn) VALUES('119304','Ralegaon','','119','1','1',now(),now());
INSERT INTO com_code(codeID, codeNameEn,codeNameMr,codeGroupID,createdBy,modifiedBy,createdOn,ModifiedOn) VALUES('119305','Ghatanji','','119','1','1',now(),now());
INSERT INTO com_code(codeID, codeNameEn,codeNameMr,codeGroupID,createdBy,modifiedBy,createdOn,ModifiedOn) VALUES('119306','Wani','','119','1','1',now(),now());
INSERT INTO com_code(codeID, codeNameEn,codeNameMr,codeGroupID,createdBy,modifiedBy,createdOn,ModifiedOn) VALUES('119307','Maregaon','','119','1','1',now(),now());
INSERT INTO com_code(codeID, codeNameEn,codeNameMr,codeGroupID,createdBy,modifiedBy,createdOn,ModifiedOn) VALUES('119308','Zari Jamani','','119','1','1',now(),now());
INSERT INTO com_code(codeID, codeNameEn,codeNameMr,codeGroupID,createdBy,modifiedBy,createdOn,ModifiedOn) VALUES('119309','Nanded','','119','1','1',now(),now());
INSERT INTO com_code(codeID, codeNameEn,codeNameMr,codeGroupID,createdBy,modifiedBy,createdOn,ModifiedOn) VALUES('119310','Ardhapur','','119','1','1',now(),now());
INSERT INTO com_code(codeID, codeNameEn,codeNameMr,codeGroupID,createdBy,modifiedBy,createdOn,ModifiedOn) VALUES('119311','Mudkhed','','119','1','1',now(),now());
INSERT INTO com_code(codeID, codeNameEn,codeNameMr,codeGroupID,createdBy,modifiedBy,createdOn,ModifiedOn) VALUES('119312','Bhokar','','119','1','1',now(),now());
INSERT INTO com_code(codeID, codeNameEn,codeNameMr,codeGroupID,createdBy,modifiedBy,createdOn,ModifiedOn) VALUES('119313','Umri','','119','1','1',now(),now());
INSERT INTO com_code(codeID, codeNameEn,codeNameMr,codeGroupID,createdBy,modifiedBy,createdOn,ModifiedOn) VALUES('119314','Loha','','119','1','1',now(),now());
INSERT INTO com_code(codeID, codeNameEn,codeNameMr,codeGroupID,createdBy,modifiedBy,createdOn,ModifiedOn) VALUES('119315','Kandhar','','119','1','1',now(),now());
INSERT INTO com_code(codeID, codeNameEn,codeNameMr,codeGroupID,createdBy,modifiedBy,createdOn,ModifiedOn) VALUES('119316','Kinwat','','119','1','1',now(),now());
INSERT INTO com_code(codeID, codeNameEn,codeNameMr,codeGroupID,createdBy,modifiedBy,createdOn,ModifiedOn) VALUES('119317','Himayatnagar','','119','1','1',now(),now());
INSERT INTO com_code(codeID, codeNameEn,codeNameMr,codeGroupID,createdBy,modifiedBy,createdOn,ModifiedOn) VALUES('119318','Hadgaon','','119','1','1',now(),now());
INSERT INTO com_code(codeID, codeNameEn,codeNameMr,codeGroupID,createdBy,modifiedBy,createdOn,ModifiedOn) VALUES('119319','Mahur','','119','1','1',now(),now());
INSERT INTO com_code(codeID, codeNameEn,codeNameMr,codeGroupID,createdBy,modifiedBy,createdOn,ModifiedOn) VALUES('119320','Deglur','','119','1','1',now(),now());
INSERT INTO com_code(codeID, codeNameEn,codeNameMr,codeGroupID,createdBy,modifiedBy,createdOn,ModifiedOn) VALUES('119321','Mukhed','','119','1','1',now(),now());
INSERT INTO com_code(codeID, codeNameEn,codeNameMr,codeGroupID,createdBy,modifiedBy,createdOn,ModifiedOn) VALUES('119322','Dharmabad','','119','1','1',now(),now());
INSERT INTO com_code(codeID, codeNameEn,codeNameMr,codeGroupID,createdBy,modifiedBy,createdOn,ModifiedOn) VALUES('119323','Biloli','','119','1','1',now(),now());
INSERT INTO com_code(codeID, codeNameEn,codeNameMr,codeGroupID,createdBy,modifiedBy,createdOn,ModifiedOn) VALUES('119324','Naigaon (Khairgaon)','','119','1','1',now(),now());
INSERT INTO com_code(codeID, codeNameEn,codeNameMr,codeGroupID,createdBy,modifiedBy,createdOn,ModifiedOn) VALUES('119325','Hingoli','','119','1','1',now(),now());
INSERT INTO com_code(codeID, codeNameEn,codeNameMr,codeGroupID,createdBy,modifiedBy,createdOn,ModifiedOn) VALUES('119326','Sengaon','','119','1','1',now(),now());
INSERT INTO com_code(codeID, codeNameEn,codeNameMr,codeGroupID,createdBy,modifiedBy,createdOn,ModifiedOn) VALUES('119327','Kalamnuri','','119','1','1',now(),now());
INSERT INTO com_code(codeID, codeNameEn,codeNameMr,codeGroupID,createdBy,modifiedBy,createdOn,ModifiedOn) VALUES('119328','Basmath','','119','1','1',now(),now());
INSERT INTO com_code(codeID, codeNameEn,codeNameMr,codeGroupID,createdBy,modifiedBy,createdOn,ModifiedOn) VALUES('119329','Aundha Nagnath','','119','1','1',now(),now());
INSERT INTO com_code(codeID, codeNameEn,codeNameMr,codeGroupID,createdBy,modifiedBy,createdOn,ModifiedOn) VALUES('119330','Parbhani','','119','1','1',now(),now());
INSERT INTO com_code(codeID, codeNameEn,codeNameMr,codeGroupID,createdBy,modifiedBy,createdOn,ModifiedOn) VALUES('119331','Sonpeth','','119','1','1',now(),now());
INSERT INTO com_code(codeID, codeNameEn,codeNameMr,codeGroupID,createdBy,modifiedBy,createdOn,ModifiedOn) VALUES('119332','Gangakhed','','119','1','1',now(),now());
INSERT INTO com_code(codeID, codeNameEn,codeNameMr,codeGroupID,createdBy,modifiedBy,createdOn,ModifiedOn) VALUES('119333','Palam','','119','1','1',now(),now());
INSERT INTO com_code(codeID, codeNameEn,codeNameMr,codeGroupID,createdBy,modifiedBy,createdOn,ModifiedOn) VALUES('119334','Purna','','119','1','1',now(),now());
INSERT INTO com_code(codeID, codeNameEn,codeNameMr,codeGroupID,createdBy,modifiedBy,createdOn,ModifiedOn) VALUES('119335','Sailu','','119','1','1',now(),now());
INSERT INTO com_code(codeID, codeNameEn,codeNameMr,codeGroupID,createdBy,modifiedBy,createdOn,ModifiedOn) VALUES('119336','Jintur','','119','1','1',now(),now());
INSERT INTO com_code(codeID, codeNameEn,codeNameMr,codeGroupID,createdBy,modifiedBy,createdOn,ModifiedOn) VALUES('119337','Manwath','','119','1','1',now(),now());
INSERT INTO com_code(codeID, codeNameEn,codeNameMr,codeGroupID,createdBy,modifiedBy,createdOn,ModifiedOn) VALUES('119338','Pathri','','119','1','1',now(),now());
INSERT INTO com_code(codeID, codeNameEn,codeNameMr,codeGroupID,createdBy,modifiedBy,createdOn,ModifiedOn) VALUES('119339','Jalna','','119','1','1',now(),now());
INSERT INTO com_code(codeID, codeNameEn,codeNameMr,codeGroupID,createdBy,modifiedBy,createdOn,ModifiedOn) VALUES('119340','Bhokardan','','119','1','1',now(),now());
INSERT INTO com_code(codeID, codeNameEn,codeNameMr,codeGroupID,createdBy,modifiedBy,createdOn,ModifiedOn) VALUES('119341','Jafrabad','','119','1','1',now(),now());
INSERT INTO com_code(codeID, codeNameEn,codeNameMr,codeGroupID,createdBy,modifiedBy,createdOn,ModifiedOn) VALUES('119342','Badnapur','','119','1','1',now(),now());
INSERT INTO com_code(codeID, codeNameEn,codeNameMr,codeGroupID,createdBy,modifiedBy,createdOn,ModifiedOn) VALUES('119343','Ambad','','119','1','1',now(),now());
INSERT INTO com_code(codeID, codeNameEn,codeNameMr,codeGroupID,createdBy,modifiedBy,createdOn,ModifiedOn) VALUES('119344','Ghansawangi','','119','1','1',now(),now());
INSERT INTO com_code(codeID, codeNameEn,codeNameMr,codeGroupID,createdBy,modifiedBy,createdOn,ModifiedOn) VALUES('119345','Partur','','119','1','1',now(),now());
INSERT INTO com_code(codeID, codeNameEn,codeNameMr,codeGroupID,createdBy,modifiedBy,createdOn,ModifiedOn) VALUES('119346','Mantha','','119','1','1',now(),now());
INSERT INTO com_code(codeID, codeNameEn,codeNameMr,codeGroupID,createdBy,modifiedBy,createdOn,ModifiedOn) VALUES('119347','Aurangabad','','119','1','1',now(),now());
INSERT INTO com_code(codeID, codeNameEn,codeNameMr,codeGroupID,createdBy,modifiedBy,createdOn,ModifiedOn) VALUES('119348','Kannad','','119','1','1',now(),now());
INSERT INTO com_code(codeID, codeNameEn,codeNameMr,codeGroupID,createdBy,modifiedBy,createdOn,ModifiedOn) VALUES('119349','Soegaon','','119','1','1',now(),now());
INSERT INTO com_code(codeID, codeNameEn,codeNameMr,codeGroupID,createdBy,modifiedBy,createdOn,ModifiedOn) VALUES('119350','Sillod','','119','1','1',now(),now());
INSERT INTO com_code(codeID, codeNameEn,codeNameMr,codeGroupID,createdBy,modifiedBy,createdOn,ModifiedOn) VALUES('119351','Phulambri','','119','1','1',now(),now());
INSERT INTO com_code(codeID, codeNameEn,codeNameMr,codeGroupID,createdBy,modifiedBy,createdOn,ModifiedOn) VALUES('119352','Khuldabad','','119','1','1',now(),now());
INSERT INTO com_code(codeID, codeNameEn,codeNameMr,codeGroupID,createdBy,modifiedBy,createdOn,ModifiedOn) VALUES('119353','Vaijapur','','119','1','1',now(),now());
INSERT INTO com_code(codeID, codeNameEn,codeNameMr,codeGroupID,createdBy,modifiedBy,createdOn,ModifiedOn) VALUES('119354','Gangapur','','119','1','1',now(),now());
INSERT INTO com_code(codeID, codeNameEn,codeNameMr,codeGroupID,createdBy,modifiedBy,createdOn,ModifiedOn) VALUES('119355','Paithan','','119','1','1',now(),now());
INSERT INTO com_code(codeID, codeNameEn,codeNameMr,codeGroupID,createdBy,modifiedBy,createdOn,ModifiedOn) VALUES('119356','Beed','','119','1','1',now(),now());
INSERT INTO com_code(codeID, codeNameEn,codeNameMr,codeGroupID,createdBy,modifiedBy,createdOn,ModifiedOn) VALUES('119357','Ashti','','119','1','1',now(),now());
INSERT INTO com_code(codeID, codeNameEn,codeNameMr,codeGroupID,createdBy,modifiedBy,createdOn,ModifiedOn) VALUES('119358','Patoda','','119','1','1',now(),now());
INSERT INTO com_code(codeID, codeNameEn,codeNameMr,codeGroupID,createdBy,modifiedBy,createdOn,ModifiedOn) VALUES('119359','Shirur-Kasar','','119','1','1',now(),now());
INSERT INTO com_code(codeID, codeNameEn,codeNameMr,codeGroupID,createdBy,modifiedBy,createdOn,ModifiedOn) VALUES('119360','Georai','','119','1','1',now(),now());
INSERT INTO com_code(codeID, codeNameEn,codeNameMr,codeGroupID,createdBy,modifiedBy,createdOn,ModifiedOn) VALUES('119361','Majalgaon','','119','1','1',now(),now());
INSERT INTO com_code(codeID, codeNameEn,codeNameMr,codeGroupID,createdBy,modifiedBy,createdOn,ModifiedOn) VALUES('119362','Wadwani','','119','1','1',now(),now());
INSERT INTO com_code(codeID, codeNameEn,codeNameMr,codeGroupID,createdBy,modifiedBy,createdOn,ModifiedOn) VALUES('119363','Kaij','','119','1','1',now(),now());
INSERT INTO com_code(codeID, codeNameEn,codeNameMr,codeGroupID,createdBy,modifiedBy,createdOn,ModifiedOn) VALUES('119364','Dharur','','119','1','1',now(),now());
INSERT INTO com_code(codeID, codeNameEn,codeNameMr,codeGroupID,createdBy,modifiedBy,createdOn,ModifiedOn) VALUES('119365','Parli','','119','1','1',now(),now());
INSERT INTO com_code(codeID, codeNameEn,codeNameMr,codeGroupID,createdBy,modifiedBy,createdOn,ModifiedOn) VALUES('119366','Ambejogai','','119','1','1',now(),now());
INSERT INTO com_code(codeID, codeNameEn,codeNameMr,codeGroupID,createdBy,modifiedBy,createdOn,ModifiedOn) VALUES('119367','Latur','','119','1','1',now(),now());
INSERT INTO com_code(codeID, codeNameEn,codeNameMr,codeGroupID,createdBy,modifiedBy,createdOn,ModifiedOn) VALUES('119368','Renapur','','119','1','1',now(),now());
INSERT INTO com_code(codeID, codeNameEn,codeNameMr,codeGroupID,createdBy,modifiedBy,createdOn,ModifiedOn) VALUES('119369','Ahmadpur','','119','1','1',now(),now());
INSERT INTO com_code(codeID, codeNameEn,codeNameMr,codeGroupID,createdBy,modifiedBy,createdOn,ModifiedOn) VALUES('119370','Jalkot','','119','1','1',now(),now());
INSERT INTO com_code(codeID, codeNameEn,codeNameMr,codeGroupID,createdBy,modifiedBy,createdOn,ModifiedOn) VALUES('119371','Chakur','','119','1','1',now(),now());
INSERT INTO com_code(codeID, codeNameEn,codeNameMr,codeGroupID,createdBy,modifiedBy,createdOn,ModifiedOn) VALUES('119372','Shirur Anantpal','','119','1','1',now(),now());
INSERT INTO com_code(codeID, codeNameEn,codeNameMr,codeGroupID,createdBy,modifiedBy,createdOn,ModifiedOn) VALUES('119373','Ausa','','119','1','1',now(),now());
INSERT INTO com_code(codeID, codeNameEn,codeNameMr,codeGroupID,createdBy,modifiedBy,createdOn,ModifiedOn) VALUES('119374','Nilanga','','119','1','1',now(),now());
INSERT INTO com_code(codeID, codeNameEn,codeNameMr,codeGroupID,createdBy,modifiedBy,createdOn,ModifiedOn) VALUES('119375','Deoni','','119','1','1',now(),now());
INSERT INTO com_code(codeID, codeNameEn,codeNameMr,codeGroupID,createdBy,modifiedBy,createdOn,ModifiedOn) VALUES('119376','Udgir','','119','1','1',now(),now());
INSERT INTO com_code(codeID, codeNameEn,codeNameMr,codeGroupID,createdBy,modifiedBy,createdOn,ModifiedOn) VALUES('119377','Osmanabad','','119','1','1',now(),now());
INSERT INTO com_code(codeID, codeNameEn,codeNameMr,codeGroupID,createdBy,modifiedBy,createdOn,ModifiedOn) VALUES('119378','Tuljapur','','119','1','1',now(),now());
INSERT INTO com_code(codeID, codeNameEn,codeNameMr,codeGroupID,createdBy,modifiedBy,createdOn,ModifiedOn) VALUES('119379','Lohara','','119','1','1',now(),now());
INSERT INTO com_code(codeID, codeNameEn,codeNameMr,codeGroupID,createdBy,modifiedBy,createdOn,ModifiedOn) VALUES('119380','Umarga','','119','1','1',now(),now());
INSERT INTO com_code(codeID, codeNameEn,codeNameMr,codeGroupID,createdBy,modifiedBy,createdOn,ModifiedOn) VALUES('119381','Bhum','','119','1','1',now(),now());
INSERT INTO com_code(codeID, codeNameEn,codeNameMr,codeGroupID,createdBy,modifiedBy,createdOn,ModifiedOn) VALUES('119382','Paranda','','119','1','1',now(),now());
INSERT INTO com_code(codeID, codeNameEn,codeNameMr,codeGroupID,createdBy,modifiedBy,createdOn,ModifiedOn) VALUES('119383','Washi','','119','1','1',now(),now());
INSERT INTO com_code(codeID, codeNameEn,codeNameMr,codeGroupID,createdBy,modifiedBy,createdOn,ModifiedOn) VALUES('119384','Kalamb','','119','1','1',now(),now());
INSERT INTO com_code(codeID, codeNameEn,codeNameMr,codeGroupID,createdBy,modifiedBy,createdOn,ModifiedOn) VALUES('119385','Solapur North','','119','1','1',now(),now());
INSERT INTO com_code(codeID, codeNameEn,codeNameMr,codeGroupID,createdBy,modifiedBy,createdOn,ModifiedOn) VALUES('119386','Solapur South','','119','1','1',now(),now());
INSERT INTO com_code(codeID, codeNameEn,codeNameMr,codeGroupID,createdBy,modifiedBy,createdOn,ModifiedOn) VALUES('119387','Akkalkot','','119','1','1',now(),now());
INSERT INTO com_code(codeID, codeNameEn,codeNameMr,codeGroupID,createdBy,modifiedBy,createdOn,ModifiedOn) VALUES('119388','Barshi','','119','1','1',now(),now());
INSERT INTO com_code(codeID, codeNameEn,codeNameMr,codeGroupID,createdBy,modifiedBy,createdOn,ModifiedOn) VALUES('119389','Madha','','119','1','1',now(),now());
INSERT INTO com_code(codeID, codeNameEn,codeNameMr,codeGroupID,createdBy,modifiedBy,createdOn,ModifiedOn) VALUES('119390','Karmala','','119','1','1',now(),now());
INSERT INTO com_code(codeID, codeNameEn,codeNameMr,codeGroupID,createdBy,modifiedBy,createdOn,ModifiedOn) VALUES('119391','Mohol','','119','1','1',now(),now());
INSERT INTO com_code(codeID, codeNameEn,codeNameMr,codeGroupID,createdBy,modifiedBy,createdOn,ModifiedOn) VALUES('119392','Pandharpur','','119','1','1',now(),now());
INSERT INTO com_code(codeID, codeNameEn,codeNameMr,codeGroupID,createdBy,modifiedBy,createdOn,ModifiedOn) VALUES('119393','Malshiras','','119','1','1',now(),now());
INSERT INTO com_code(codeID, codeNameEn,codeNameMr,codeGroupID,createdBy,modifiedBy,createdOn,ModifiedOn) VALUES('119394','Sangole','','119','1','1',now(),now());
INSERT INTO com_code(codeID, codeNameEn,codeNameMr,codeGroupID,createdBy,modifiedBy,createdOn,ModifiedOn) VALUES('119395','Mangalvedhe','','119','1','1',now(),now());
INSERT INTO com_code(codeID, codeNameEn,codeNameMr,codeGroupID,createdBy,modifiedBy,createdOn,ModifiedOn) VALUES('119396','Nagar','','119','1','1',now(),now());
INSERT INTO com_code(codeID, codeNameEn,codeNameMr,codeGroupID,createdBy,modifiedBy,createdOn,ModifiedOn) VALUES('119397','Shevgaon','','119','1','1',now(),now());
INSERT INTO com_code(codeID, codeNameEn,codeNameMr,codeGroupID,createdBy,modifiedBy,createdOn,ModifiedOn) VALUES('119398','Pathardi','','119','1','1',now(),now());
INSERT INTO com_code(codeID, codeNameEn,codeNameMr,codeGroupID,createdBy,modifiedBy,createdOn,ModifiedOn) VALUES('119399','Parner','','119','1','1',now(),now());
INSERT INTO com_code(codeID, codeNameEn,codeNameMr,codeGroupID,createdBy,modifiedBy,createdOn,ModifiedOn) VALUES('119400','Sangamner','','119','1','1',now(),now());
INSERT INTO com_code(codeID, codeNameEn,codeNameMr,codeGroupID,createdBy,modifiedBy,createdOn,ModifiedOn) VALUES('119401','Kopargaon','','119','1','1',now(),now());
INSERT INTO com_code(codeID, codeNameEn,codeNameMr,codeGroupID,createdBy,modifiedBy,createdOn,ModifiedOn) VALUES('119402','Akole','','119','1','1',now(),now());
INSERT INTO com_code(codeID, codeNameEn,codeNameMr,codeGroupID,createdBy,modifiedBy,createdOn,ModifiedOn) VALUES('119403','Shrirampur','','119','1','1',now(),now());
INSERT INTO com_code(codeID, codeNameEn,codeNameMr,codeGroupID,createdBy,modifiedBy,createdOn,ModifiedOn) VALUES('119404','Nevasa','','119','1','1',now(),now());
INSERT INTO com_code(codeID, codeNameEn,codeNameMr,codeGroupID,createdBy,modifiedBy,createdOn,ModifiedOn) VALUES('119405','Rahata','','119','1','1',now(),now());
INSERT INTO com_code(codeID, codeNameEn,codeNameMr,codeGroupID,createdBy,modifiedBy,createdOn,ModifiedOn) VALUES('119406','Rahuri','','119','1','1',now(),now());
INSERT INTO com_code(codeID, codeNameEn,codeNameMr,codeGroupID,createdBy,modifiedBy,createdOn,ModifiedOn) VALUES('119407','Shrigonda','','119','1','1',now(),now());
INSERT INTO com_code(codeID, codeNameEn,codeNameMr,codeGroupID,createdBy,modifiedBy,createdOn,ModifiedOn) VALUES('119408','Karjat','','119','1','1',now(),now());
INSERT INTO com_code(codeID, codeNameEn,codeNameMr,codeGroupID,createdBy,modifiedBy,createdOn,ModifiedOn) VALUES('119409','Jamkhed','','119','1','1',now(),now());
INSERT INTO com_code(codeID, codeNameEn,codeNameMr,codeGroupID,createdBy,modifiedBy,createdOn,ModifiedOn) VALUES('119410','Pune City','','119','1','1',now(),now());
INSERT INTO com_code(codeID, codeNameEn,codeNameMr,codeGroupID,createdBy,modifiedBy,createdOn,ModifiedOn) VALUES('119411','Haveli','','119','1','1',now(),now());
INSERT INTO com_code(codeID, codeNameEn,codeNameMr,codeGroupID,createdBy,modifiedBy,createdOn,ModifiedOn) VALUES('119412','Khed (Rajgurunagar)','','119','1','1',now(),now());
INSERT INTO com_code(codeID, codeNameEn,codeNameMr,codeGroupID,createdBy,modifiedBy,createdOn,ModifiedOn) VALUES('119413','Junnar','','119','1','1',now(),now());
INSERT INTO com_code(codeID, codeNameEn,codeNameMr,codeGroupID,createdBy,modifiedBy,createdOn,ModifiedOn) VALUES('119414','Ambegaon (Ghodegaon)','','119','1','1',now(),now());
INSERT INTO com_code(codeID, codeNameEn,codeNameMr,codeGroupID,createdBy,modifiedBy,createdOn,ModifiedOn) VALUES('119415','Maval (Vadgaon)','','119','1','1',now(),now());
INSERT INTO com_code(codeID, codeNameEn,codeNameMr,codeGroupID,createdBy,modifiedBy,createdOn,ModifiedOn) VALUES('119416','Mulshi (Paud)','','119','1','1',now(),now());
INSERT INTO com_code(codeID, codeNameEn,codeNameMr,codeGroupID,createdBy,modifiedBy,createdOn,ModifiedOn) VALUES('119417','Shirur','','119','1','1',now(),now());
INSERT INTO com_code(codeID, codeNameEn,codeNameMr,codeGroupID,createdBy,modifiedBy,createdOn,ModifiedOn) VALUES('119418','Purandhar (Saswad)','','119','1','1',now(),now());
INSERT INTO com_code(codeID, codeNameEn,codeNameMr,codeGroupID,createdBy,modifiedBy,createdOn,ModifiedOn) VALUES('119419','Velhe','','119','1','1',now(),now());
INSERT INTO com_code(codeID, codeNameEn,codeNameMr,codeGroupID,createdBy,modifiedBy,createdOn,ModifiedOn) VALUES('119420','Bhor','','119','1','1',now(),now());
INSERT INTO com_code(codeID, codeNameEn,codeNameMr,codeGroupID,createdBy,modifiedBy,createdOn,ModifiedOn) VALUES('119421','Baramati','','119','1','1',now(),now());
INSERT INTO com_code(codeID, codeNameEn,codeNameMr,codeGroupID,createdBy,modifiedBy,createdOn,ModifiedOn) VALUES('119422','Indapur','','119','1','1',now(),now());
INSERT INTO com_code(codeID, codeNameEn,codeNameMr,codeGroupID,createdBy,modifiedBy,createdOn,ModifiedOn) VALUES('119423','Daund','','119','1','1',now(),now());
INSERT INTO com_code(codeID, codeNameEn,codeNameMr,codeGroupID,createdBy,modifiedBy,createdOn,ModifiedOn) VALUES('119424','Satara','','119','1','1',now(),now());
INSERT INTO com_code(codeID, codeNameEn,codeNameMr,codeGroupID,createdBy,modifiedBy,createdOn,ModifiedOn) VALUES('119425','Jaoli','','119','1','1',now(),now());
INSERT INTO com_code(codeID, codeNameEn,codeNameMr,codeGroupID,createdBy,modifiedBy,createdOn,ModifiedOn) VALUES('119426','Koregaon','','119','1','1',now(),now());
INSERT INTO com_code(codeID, codeNameEn,codeNameMr,codeGroupID,createdBy,modifiedBy,createdOn,ModifiedOn) VALUES('119427','Wai','','119','1','1',now(),now());
INSERT INTO com_code(codeID, codeNameEn,codeNameMr,codeGroupID,createdBy,modifiedBy,createdOn,ModifiedOn) VALUES('119428','Mahabaleshwar','','119','1','1',now(),now());
INSERT INTO com_code(codeID, codeNameEn,codeNameMr,codeGroupID,createdBy,modifiedBy,createdOn,ModifiedOn) VALUES('119429','Khandala','','119','1','1',now(),now());
INSERT INTO com_code(codeID, codeNameEn,codeNameMr,codeGroupID,createdBy,modifiedBy,createdOn,ModifiedOn) VALUES('119430','Phaltan','','119','1','1',now(),now());
INSERT INTO com_code(codeID, codeNameEn,codeNameMr,codeGroupID,createdBy,modifiedBy,createdOn,ModifiedOn) VALUES('119431','Maan (Dahiwadi)','','119','1','1',now(),now());
INSERT INTO com_code(codeID, codeNameEn,codeNameMr,codeGroupID,createdBy,modifiedBy,createdOn,ModifiedOn) VALUES('119432','Khatav (Vaduj)','','119','1','1',now(),now());
INSERT INTO com_code(codeID, codeNameEn,codeNameMr,codeGroupID,createdBy,modifiedBy,createdOn,ModifiedOn) VALUES('119433','Patan','','119','1','1',now(),now());
INSERT INTO com_code(codeID, codeNameEn,codeNameMr,codeGroupID,createdBy,modifiedBy,createdOn,ModifiedOn) VALUES('119434','Karad','','119','1','1',now(),now());
INSERT INTO com_code(codeID, codeNameEn,codeNameMr,codeGroupID,createdBy,modifiedBy,createdOn,ModifiedOn) VALUES('119435','Miraj','','119','1','1',now(),now());
INSERT INTO com_code(codeID, codeNameEn,codeNameMr,codeGroupID,createdBy,modifiedBy,createdOn,ModifiedOn) VALUES('119436','Kavathe-Mahankal','','119','1','1',now(),now());
INSERT INTO com_code(codeID, codeNameEn,codeNameMr,codeGroupID,createdBy,modifiedBy,createdOn,ModifiedOn) VALUES('119437','Tasgaon','','119','1','1',now(),now());
INSERT INTO com_code(codeID, codeNameEn,codeNameMr,codeGroupID,createdBy,modifiedBy,createdOn,ModifiedOn) VALUES('119438','Jat','','119','1','1',now(),now());
INSERT INTO com_code(codeID, codeNameEn,codeNameMr,codeGroupID,createdBy,modifiedBy,createdOn,ModifiedOn) VALUES('119439','Walwa (Islampur)','','119','1','1',now(),now());
INSERT INTO com_code(codeID, codeNameEn,codeNameMr,codeGroupID,createdBy,modifiedBy,createdOn,ModifiedOn) VALUES('119440','Shirala','','119','1','1',now(),now());
INSERT INTO com_code(codeID, codeNameEn,codeNameMr,codeGroupID,createdBy,modifiedBy,createdOn,ModifiedOn) VALUES('119441','Khanapur-Vita','','119','1','1',now(),now());
INSERT INTO com_code(codeID, codeNameEn,codeNameMr,codeGroupID,createdBy,modifiedBy,createdOn,ModifiedOn) VALUES('119442','Atpadi','','119','1','1',now(),now());
INSERT INTO com_code(codeID, codeNameEn,codeNameMr,codeGroupID,createdBy,modifiedBy,createdOn,ModifiedOn) VALUES('119443','Palus','','119','1','1',now(),now());
INSERT INTO com_code(codeID, codeNameEn,codeNameMr,codeGroupID,createdBy,modifiedBy,createdOn,ModifiedOn) VALUES('119444','Kadegaon','','119','1','1',now(),now());
INSERT INTO com_code(codeID, codeNameEn,codeNameMr,codeGroupID,createdBy,modifiedBy,createdOn,ModifiedOn) VALUES('119445','Karvir','','119','1','1',now(),now());
INSERT INTO com_code(codeID, codeNameEn,codeNameMr,codeGroupID,createdBy,modifiedBy,createdOn,ModifiedOn) VALUES('119446','Panhala','','119','1','1',now(),now());
INSERT INTO com_code(codeID, codeNameEn,codeNameMr,codeGroupID,createdBy,modifiedBy,createdOn,ModifiedOn) VALUES('119447','Shahuwadi','','119','1','1',now(),now());
INSERT INTO com_code(codeID, codeNameEn,codeNameMr,codeGroupID,createdBy,modifiedBy,createdOn,ModifiedOn) VALUES('119448','Kagal','','119','1','1',now(),now());
INSERT INTO com_code(codeID, codeNameEn,codeNameMr,codeGroupID,createdBy,modifiedBy,createdOn,ModifiedOn) VALUES('119449','Hatkanangale','','119','1','1',now(),now());
INSERT INTO com_code(codeID, codeNameEn,codeNameMr,codeGroupID,createdBy,modifiedBy,createdOn,ModifiedOn) VALUES('119450','Shirol','','119','1','1',now(),now());
INSERT INTO com_code(codeID, codeNameEn,codeNameMr,codeGroupID,createdBy,modifiedBy,createdOn,ModifiedOn) VALUES('119451','Radhanagari','','119','1','1',now(),now());
INSERT INTO com_code(codeID, codeNameEn,codeNameMr,codeGroupID,createdBy,modifiedBy,createdOn,ModifiedOn) VALUES('119452','Gaganbawada','','119','1','1',now(),now());
INSERT INTO com_code(codeID, codeNameEn,codeNameMr,codeGroupID,createdBy,modifiedBy,createdOn,ModifiedOn) VALUES('119453','Bhudargad','','119','1','1',now(),now());
INSERT INTO com_code(codeID, codeNameEn,codeNameMr,codeGroupID,createdBy,modifiedBy,createdOn,ModifiedOn) VALUES('119454','Gadhinglaj','','119','1','1',now(),now());
INSERT INTO com_code(codeID, codeNameEn,codeNameMr,codeGroupID,createdBy,modifiedBy,createdOn,ModifiedOn) VALUES('119455','Chandgad','','119','1','1',now(),now());
INSERT INTO com_code(codeID, codeNameEn,codeNameMr,codeGroupID,createdBy,modifiedBy,createdOn,ModifiedOn) VALUES('119456','Ajra','','119','1','1',now(),now());



-- create table for calendar

BEGIN;
--
-- Create model districtBlockMapping
--
CREATE TABLE `evt_districtBlockMapping` (`districtBlockMappingID` integer AUTO_INCREMENT NOT NULL PRIMARY KEY, `blockCodeID` integer NOT NULL, `districtCodeID` integer NOT NULL);
--
-- Create model event
--
CREATE TABLE `evt_event` (`eventID` integer AUTO_INCREMENT NOT NULL PRIMARY KEY, `createdOn` datetime NOT NULL, `categoryCodeID` integer NOT NULL, `createdBy` integer NOT NULL);
--
-- Create model eventDetail
--
CREATE TABLE `evt_eventDetail` (`eventDetailID` integer AUTO_INCREMENT NOT NULL PRIMARY KEY, `date` datetime NOT NULL, `engLocation` varchar(255) NULL, `marLocation` varchar(255) NULL, `engTrainer` varchar(255) NULL, `marTrainer` varchar(255) NULL, `createdOn` datetime NOT NULL, `modifiedOn` datetime NOT NULL, `blockCodeID` integer NOT NULL, `createdBy` integer NOT NULL, `districtCodeID` integer NOT NULL, `eventID` integer NOT NULL, `modifiedBy` integer NOT NULL, `statusCodeID` integer NOT NULL);
--
-- Create model eventInfo
--
CREATE TABLE `evt_eventInfo` (`eventInfoID` integer AUTO_INCREMENT NOT NULL PRIMARY KEY, `eventTitle` varchar(2555) NULL, `eventDescription` longtext NULL, `appLanguageCodeID` integer NOT NULL, `eventID` integer NOT NULL);
ALTER TABLE `evt_districtBlockMapping` ADD CONSTRAINT `evt_districtBlockMapping_blockCodeID_42da7e59_fk_com_code_codeID` FOREIGN KEY (`blockCodeID`) REFERENCES `com_code` (`codeID`);
ALTER TABLE `evt_districtBlockMapping` ADD CONSTRAINT `evt_districtBlockMapp_districtCodeID_1c8dfa10_fk_com_code_codeID` FOREIGN KEY (`districtCodeID`) REFERENCES `com_code` (`codeID`);
ALTER TABLE `evt_event` ADD CONSTRAINT `evt_event_categoryCodeID_faec4658_fk_com_code_codeID` FOREIGN KEY (`categoryCodeID`) REFERENCES `com_code` (`codeID`);
ALTER TABLE `evt_event` ADD CONSTRAINT `evt_event_createdBy_44db1619_fk_usr_User_userID` FOREIGN KEY (`createdBy`) REFERENCES `usr_User` (`userID`);
ALTER TABLE `evt_eventDetail` ADD CONSTRAINT `evt_eventDetail_blockCodeID_d8159648_fk_com_code_codeID` FOREIGN KEY (`blockCodeID`) REFERENCES `com_code` (`codeID`);
ALTER TABLE `evt_eventDetail` ADD CONSTRAINT `evt_eventDetail_createdBy_83916db0_fk_usr_User_userID` FOREIGN KEY (`createdBy`) REFERENCES `usr_User` (`userID`);
ALTER TABLE `evt_eventDetail` ADD CONSTRAINT `evt_eventDetail_districtCodeID_ffaa9931_fk_com_code_codeID` FOREIGN KEY (`districtCodeID`) REFERENCES `com_code` (`codeID`);
ALTER TABLE `evt_eventDetail` ADD CONSTRAINT `evt_eventDetail_eventID_03186ba5_fk_evt_event_eventID` FOREIGN KEY (`eventID`) REFERENCES `evt_event` (`eventID`);
ALTER TABLE `evt_eventDetail` ADD CONSTRAINT `evt_eventDetail_modifiedBy_2c1e9336_fk_usr_User_userID` FOREIGN KEY (`modifiedBy`) REFERENCES `usr_User` (`userID`);
ALTER TABLE `evt_eventDetail` ADD CONSTRAINT `evt_eventDetail_statusCodeID_ec443d51_fk_com_code_codeID` FOREIGN KEY (`statusCodeID`) REFERENCES `com_code` (`codeID`);
ALTER TABLE `evt_eventInfo` ADD CONSTRAINT `evt_eventInfo_appLanguageCodeID_148a2ef0_fk_com_code_codeID` FOREIGN KEY (`appLanguageCodeID`) REFERENCES `com_code` (`codeID`);
ALTER TABLE `evt_eventInfo` ADD CONSTRAINT `evt_eventInfo_eventID_b72119d5_fk_evt_event_eventID` FOREIGN KEY (`eventID`) REFERENCES `evt_event` (`eventID`);

COMMIT;


-- Mapp block to the respective district

INSERT INTO evt_districtBlockMapping(blockCodeID, districtCodeID) VALUES('119100','102129');
INSERT INTO evt_districtBlockMapping(blockCodeID, districtCodeID) VALUES('119101','102129');
INSERT INTO evt_districtBlockMapping(blockCodeID, districtCodeID) VALUES('119102','102129');
INSERT INTO evt_districtBlockMapping(blockCodeID, districtCodeID) VALUES('119103','102129');
INSERT INTO evt_districtBlockMapping(blockCodeID, districtCodeID) VALUES('119104','102129');
INSERT INTO evt_districtBlockMapping(blockCodeID, districtCodeID) VALUES('119105','102129');
INSERT INTO evt_districtBlockMapping(blockCodeID, districtCodeID) VALUES('119106','102129');
INSERT INTO evt_districtBlockMapping(blockCodeID, districtCodeID) VALUES('119107','102129');
INSERT INTO evt_districtBlockMapping(blockCodeID, districtCodeID) VALUES('119108','102126');
INSERT INTO evt_districtBlockMapping(blockCodeID, districtCodeID) VALUES('119109','102126');
INSERT INTO evt_districtBlockMapping(blockCodeID, districtCodeID) VALUES('119110','102126');
INSERT INTO evt_districtBlockMapping(blockCodeID, districtCodeID) VALUES('119111','102126');
INSERT INTO evt_districtBlockMapping(blockCodeID, districtCodeID) VALUES('119112','102126');
INSERT INTO evt_districtBlockMapping(blockCodeID, districtCodeID) VALUES('119113','102126');
INSERT INTO evt_districtBlockMapping(blockCodeID, districtCodeID) VALUES('119114','102126');
INSERT INTO evt_districtBlockMapping(blockCodeID, districtCodeID) VALUES('119115','102126');
INSERT INTO evt_districtBlockMapping(blockCodeID, districtCodeID) VALUES('119116','102126');
INSERT INTO evt_districtBlockMapping(blockCodeID, districtCodeID) VALUES('119117','102125');
INSERT INTO evt_districtBlockMapping(blockCodeID, districtCodeID) VALUES('119118','102125');
INSERT INTO evt_districtBlockMapping(blockCodeID, districtCodeID) VALUES('119119','102125');
INSERT INTO evt_districtBlockMapping(blockCodeID, districtCodeID) VALUES('119120','102125');
INSERT INTO evt_districtBlockMapping(blockCodeID, districtCodeID) VALUES('119121','102125');
INSERT INTO evt_districtBlockMapping(blockCodeID, districtCodeID) VALUES('119122','102125');
INSERT INTO evt_districtBlockMapping(blockCodeID, districtCodeID) VALUES('119123','102125');
INSERT INTO evt_districtBlockMapping(blockCodeID, districtCodeID) VALUES('119124','102125');
INSERT INTO evt_districtBlockMapping(blockCodeID, districtCodeID) VALUES('119125','102125');
INSERT INTO evt_districtBlockMapping(blockCodeID, districtCodeID) VALUES('119126','102125');
INSERT INTO evt_districtBlockMapping(blockCodeID, districtCodeID) VALUES('119127','102125');
INSERT INTO evt_districtBlockMapping(blockCodeID, districtCodeID) VALUES('119128','102125');
INSERT INTO evt_districtBlockMapping(blockCodeID, districtCodeID) VALUES('119129','102125');
INSERT INTO evt_districtBlockMapping(blockCodeID, districtCodeID) VALUES('119130','102125');
INSERT INTO evt_districtBlockMapping(blockCodeID, districtCodeID) VALUES('119131','102125');
INSERT INTO evt_districtBlockMapping(blockCodeID, districtCodeID) VALUES('119132','102117');
INSERT INTO evt_districtBlockMapping(blockCodeID, districtCodeID) VALUES('119133','102117');
INSERT INTO evt_districtBlockMapping(blockCodeID, districtCodeID) VALUES('119134','102117');
INSERT INTO evt_districtBlockMapping(blockCodeID, districtCodeID) VALUES('119135','102131');
INSERT INTO evt_districtBlockMapping(blockCodeID, districtCodeID) VALUES('119136','102131');
INSERT INTO evt_districtBlockMapping(blockCodeID, districtCodeID) VALUES('119137','102131');
INSERT INTO evt_districtBlockMapping(blockCodeID, districtCodeID) VALUES('119138','102131');
INSERT INTO evt_districtBlockMapping(blockCodeID, districtCodeID) VALUES('119139','102131');
INSERT INTO evt_districtBlockMapping(blockCodeID, districtCodeID) VALUES('119140','102131');
INSERT INTO evt_districtBlockMapping(blockCodeID, districtCodeID) VALUES('119141','102131');
INSERT INTO evt_districtBlockMapping(blockCodeID, districtCodeID) VALUES('119142','102135');
INSERT INTO evt_districtBlockMapping(blockCodeID, districtCodeID) VALUES('119143','102135');
INSERT INTO evt_districtBlockMapping(blockCodeID, districtCodeID) VALUES('119144','102135');
INSERT INTO evt_districtBlockMapping(blockCodeID, districtCodeID) VALUES('119145','102135');
INSERT INTO evt_districtBlockMapping(blockCodeID, districtCodeID) VALUES('119146','102135');
INSERT INTO evt_districtBlockMapping(blockCodeID, districtCodeID) VALUES('119147','102135');
INSERT INTO evt_districtBlockMapping(blockCodeID, districtCodeID) VALUES('119148','102135');
INSERT INTO evt_districtBlockMapping(blockCodeID, districtCodeID) VALUES('119149','102135');
INSERT INTO evt_districtBlockMapping(blockCodeID, districtCodeID) VALUES('119150','102121');
INSERT INTO evt_districtBlockMapping(blockCodeID, districtCodeID) VALUES('119151','102121');
INSERT INTO evt_districtBlockMapping(blockCodeID, districtCodeID) VALUES('119152','102121');
INSERT INTO evt_districtBlockMapping(blockCodeID, districtCodeID) VALUES('119153','102121');
INSERT INTO evt_districtBlockMapping(blockCodeID, districtCodeID) VALUES('119154','102121');
INSERT INTO evt_districtBlockMapping(blockCodeID, districtCodeID) VALUES('119155','102121');
INSERT INTO evt_districtBlockMapping(blockCodeID, districtCodeID) VALUES('119156','102121');
INSERT INTO evt_districtBlockMapping(blockCodeID, districtCodeID) VALUES('119157','102121');
INSERT INTO evt_districtBlockMapping(blockCodeID, districtCodeID) VALUES('119158','102121');
INSERT INTO evt_districtBlockMapping(blockCodeID, districtCodeID) VALUES('119159','102121');
INSERT INTO evt_districtBlockMapping(blockCodeID, districtCodeID) VALUES('119160','102121');
INSERT INTO evt_districtBlockMapping(blockCodeID, districtCodeID) VALUES('119161','102121');
INSERT INTO evt_districtBlockMapping(blockCodeID, districtCodeID) VALUES('119162','102121');
INSERT INTO evt_districtBlockMapping(blockCodeID, districtCodeID) VALUES('119163','102121');
INSERT INTO evt_districtBlockMapping(blockCodeID, districtCodeID) VALUES('119164','102121');
INSERT INTO evt_districtBlockMapping(blockCodeID, districtCodeID) VALUES('119165','102120');
INSERT INTO evt_districtBlockMapping(blockCodeID, districtCodeID) VALUES('119166','102120');
INSERT INTO evt_districtBlockMapping(blockCodeID, districtCodeID) VALUES('119167','102120');
INSERT INTO evt_districtBlockMapping(blockCodeID, districtCodeID) VALUES('119168','102120');
INSERT INTO evt_districtBlockMapping(blockCodeID, districtCodeID) VALUES('119169','102120');
INSERT INTO evt_districtBlockMapping(blockCodeID, districtCodeID) VALUES('119170','102120');
INSERT INTO evt_districtBlockMapping(blockCodeID, districtCodeID) VALUES('119171','102108');
INSERT INTO evt_districtBlockMapping(blockCodeID, districtCodeID) VALUES('119172','102108');
INSERT INTO evt_districtBlockMapping(blockCodeID, districtCodeID) VALUES('119173','102108');
INSERT INTO evt_districtBlockMapping(blockCodeID, districtCodeID) VALUES('119174','102108');
INSERT INTO evt_districtBlockMapping(blockCodeID, districtCodeID) VALUES('119175','102112');
INSERT INTO evt_districtBlockMapping(blockCodeID, districtCodeID) VALUES('119176','102112');
INSERT INTO evt_districtBlockMapping(blockCodeID, districtCodeID) VALUES('119177','102112');
INSERT INTO evt_districtBlockMapping(blockCodeID, districtCodeID) VALUES('119178','102112');
INSERT INTO evt_districtBlockMapping(blockCodeID, districtCodeID) VALUES('119179','102112');
INSERT INTO evt_districtBlockMapping(blockCodeID, districtCodeID) VALUES('119180','102112');
INSERT INTO evt_districtBlockMapping(blockCodeID, districtCodeID) VALUES('119181','102112');
INSERT INTO evt_districtBlockMapping(blockCodeID, districtCodeID) VALUES('119182','102112');
INSERT INTO evt_districtBlockMapping(blockCodeID, districtCodeID) VALUES('119183','102112');
INSERT INTO evt_districtBlockMapping(blockCodeID, districtCodeID) VALUES('119184','102112');
INSERT INTO evt_districtBlockMapping(blockCodeID, districtCodeID) VALUES('119185','102112');
INSERT INTO evt_districtBlockMapping(blockCodeID, districtCodeID) VALUES('119186','102112');
INSERT INTO evt_districtBlockMapping(blockCodeID, districtCodeID) VALUES('119187','102112');
INSERT INTO evt_districtBlockMapping(blockCodeID, districtCodeID) VALUES('119188','102112');
INSERT INTO evt_districtBlockMapping(blockCodeID, districtCodeID) VALUES('119189','102112');
INSERT INTO evt_districtBlockMapping(blockCodeID, districtCodeID) VALUES('119190','102106');
INSERT INTO evt_districtBlockMapping(blockCodeID, districtCodeID) VALUES('119191','102106');
INSERT INTO evt_districtBlockMapping(blockCodeID, districtCodeID) VALUES('119192','102106');
INSERT INTO evt_districtBlockMapping(blockCodeID, districtCodeID) VALUES('119193','102106');
INSERT INTO evt_districtBlockMapping(blockCodeID, districtCodeID) VALUES('119194','102106');
INSERT INTO evt_districtBlockMapping(blockCodeID, districtCodeID) VALUES('119195','102106');
INSERT INTO evt_districtBlockMapping(blockCodeID, districtCodeID) VALUES('119196','102106');
INSERT INTO evt_districtBlockMapping(blockCodeID, districtCodeID) VALUES('119197','102106');
INSERT INTO evt_districtBlockMapping(blockCodeID, districtCodeID) VALUES('119198','102106');
INSERT INTO evt_districtBlockMapping(blockCodeID, districtCodeID) VALUES('119199','102106');
INSERT INTO evt_districtBlockMapping(blockCodeID, districtCodeID) VALUES('119200','102106');
INSERT INTO evt_districtBlockMapping(blockCodeID, districtCodeID) VALUES('119201','102106');
INSERT INTO evt_districtBlockMapping(blockCodeID, districtCodeID) VALUES('119202','102106');
INSERT INTO evt_districtBlockMapping(blockCodeID, districtCodeID) VALUES('119203','102101');
INSERT INTO evt_districtBlockMapping(blockCodeID, districtCodeID) VALUES('119204','102101');
INSERT INTO evt_districtBlockMapping(blockCodeID, districtCodeID) VALUES('119205','102101');
INSERT INTO evt_districtBlockMapping(blockCodeID, districtCodeID) VALUES('119206','102101');
INSERT INTO evt_districtBlockMapping(blockCodeID, districtCodeID) VALUES('119207','102101');
INSERT INTO evt_districtBlockMapping(blockCodeID, districtCodeID) VALUES('119208','102101');
INSERT INTO evt_districtBlockMapping(blockCodeID, districtCodeID) VALUES('119209','102101');
INSERT INTO evt_districtBlockMapping(blockCodeID, districtCodeID) VALUES('119210','102133');
INSERT INTO evt_districtBlockMapping(blockCodeID, districtCodeID) VALUES('119211','102133');
INSERT INTO evt_districtBlockMapping(blockCodeID, districtCodeID) VALUES('119212','102133');
INSERT INTO evt_districtBlockMapping(blockCodeID, districtCodeID) VALUES('119213','102133');
INSERT INTO evt_districtBlockMapping(blockCodeID, districtCodeID) VALUES('119214','102133');
INSERT INTO evt_districtBlockMapping(blockCodeID, districtCodeID) VALUES('119215','102133');
INSERT INTO evt_districtBlockMapping(blockCodeID, districtCodeID) VALUES('119216','102102');
INSERT INTO evt_districtBlockMapping(blockCodeID, districtCodeID) VALUES('119217','102102');
INSERT INTO evt_districtBlockMapping(blockCodeID, districtCodeID) VALUES('119218','102102');
INSERT INTO evt_districtBlockMapping(blockCodeID, districtCodeID) VALUES('119219','102102');
INSERT INTO evt_districtBlockMapping(blockCodeID, districtCodeID) VALUES('119220','102102');
INSERT INTO evt_districtBlockMapping(blockCodeID, districtCodeID) VALUES('119221','102102');
INSERT INTO evt_districtBlockMapping(blockCodeID, districtCodeID) VALUES('119222','102102');
INSERT INTO evt_districtBlockMapping(blockCodeID, districtCodeID) VALUES('119223','102102');
INSERT INTO evt_districtBlockMapping(blockCodeID, districtCodeID) VALUES('119224','102102');
INSERT INTO evt_districtBlockMapping(blockCodeID, districtCodeID) VALUES('119225','102102');
INSERT INTO evt_districtBlockMapping(blockCodeID, districtCodeID) VALUES('119226','102102');
INSERT INTO evt_districtBlockMapping(blockCodeID, districtCodeID) VALUES('119227','102102');
INSERT INTO evt_districtBlockMapping(blockCodeID, districtCodeID) VALUES('119228','102102');
INSERT INTO evt_districtBlockMapping(blockCodeID, districtCodeID) VALUES('119229','102102');
INSERT INTO evt_districtBlockMapping(blockCodeID, districtCodeID) VALUES('119230','102132');
INSERT INTO evt_districtBlockMapping(blockCodeID, districtCodeID) VALUES('119231','102132');
INSERT INTO evt_districtBlockMapping(blockCodeID, districtCodeID) VALUES('119232','102132');
INSERT INTO evt_districtBlockMapping(blockCodeID, districtCodeID) VALUES('119233','102132');
INSERT INTO evt_districtBlockMapping(blockCodeID, districtCodeID) VALUES('119234','102132');
INSERT INTO evt_districtBlockMapping(blockCodeID, districtCodeID) VALUES('119235','102132');
INSERT INTO evt_districtBlockMapping(blockCodeID, districtCodeID) VALUES('119236','102132');
INSERT INTO evt_districtBlockMapping(blockCodeID, districtCodeID) VALUES('119237','102132');
INSERT INTO evt_districtBlockMapping(blockCodeID, districtCodeID) VALUES('119238','102118');
INSERT INTO evt_districtBlockMapping(blockCodeID, districtCodeID) VALUES('119239','102118');
INSERT INTO evt_districtBlockMapping(blockCodeID, districtCodeID) VALUES('119240','102118');
INSERT INTO evt_districtBlockMapping(blockCodeID, districtCodeID) VALUES('119241','102118');
INSERT INTO evt_districtBlockMapping(blockCodeID, districtCodeID) VALUES('119242','102118');
INSERT INTO evt_districtBlockMapping(blockCodeID, districtCodeID) VALUES('119243','102118');
INSERT INTO evt_districtBlockMapping(blockCodeID, districtCodeID) VALUES('119244','102118');
INSERT INTO evt_districtBlockMapping(blockCodeID, districtCodeID) VALUES('119245','102118');
INSERT INTO evt_districtBlockMapping(blockCodeID, districtCodeID) VALUES('119246','102118');
INSERT INTO evt_districtBlockMapping(blockCodeID, districtCodeID) VALUES('119247','102118');
INSERT INTO evt_districtBlockMapping(blockCodeID, districtCodeID) VALUES('119248','102118');
INSERT INTO evt_districtBlockMapping(blockCodeID, districtCodeID) VALUES('119249','102118');
INSERT INTO evt_districtBlockMapping(blockCodeID, districtCodeID) VALUES('119250','102118');
INSERT INTO evt_districtBlockMapping(blockCodeID, districtCodeID) VALUES('119251','102118');
INSERT INTO evt_districtBlockMapping(blockCodeID, districtCodeID) VALUES('119252','102105');
INSERT INTO evt_districtBlockMapping(blockCodeID, districtCodeID) VALUES('119253','102105');
INSERT INTO evt_districtBlockMapping(blockCodeID, districtCodeID) VALUES('119254','102105');
INSERT INTO evt_districtBlockMapping(blockCodeID, districtCodeID) VALUES('119255','102105');
INSERT INTO evt_districtBlockMapping(blockCodeID, districtCodeID) VALUES('119256','102105');
INSERT INTO evt_districtBlockMapping(blockCodeID, districtCodeID) VALUES('119257','102105');
INSERT INTO evt_districtBlockMapping(blockCodeID, districtCodeID) VALUES('119258','102105');
INSERT INTO evt_districtBlockMapping(blockCodeID, districtCodeID) VALUES('119259','102110');
INSERT INTO evt_districtBlockMapping(blockCodeID, districtCodeID) VALUES('119260','102110');
INSERT INTO evt_districtBlockMapping(blockCodeID, districtCodeID) VALUES('119261','102110');
INSERT INTO evt_districtBlockMapping(blockCodeID, districtCodeID) VALUES('119262','102110');
INSERT INTO evt_districtBlockMapping(blockCodeID, districtCodeID) VALUES('119263','102110');
INSERT INTO evt_districtBlockMapping(blockCodeID, districtCodeID) VALUES('119264','102110');
INSERT INTO evt_districtBlockMapping(blockCodeID, districtCodeID) VALUES('119265','102110');
INSERT INTO evt_districtBlockMapping(blockCodeID, districtCodeID) VALUES('119266','102110');
INSERT INTO evt_districtBlockMapping(blockCodeID, districtCodeID) VALUES('119267','102109');
INSERT INTO evt_districtBlockMapping(blockCodeID, districtCodeID) VALUES('119268','102109');
INSERT INTO evt_districtBlockMapping(blockCodeID, districtCodeID) VALUES('119269','102109');
INSERT INTO evt_districtBlockMapping(blockCodeID, districtCodeID) VALUES('119270','102109');
INSERT INTO evt_districtBlockMapping(blockCodeID, districtCodeID) VALUES('119271','102109');
INSERT INTO evt_districtBlockMapping(blockCodeID, districtCodeID) VALUES('119272','102109');
INSERT INTO evt_districtBlockMapping(blockCodeID, districtCodeID) VALUES('119273','102109');
INSERT INTO evt_districtBlockMapping(blockCodeID, districtCodeID) VALUES('119274','102109');
INSERT INTO evt_districtBlockMapping(blockCodeID, districtCodeID) VALUES('119275','102109');
INSERT INTO evt_districtBlockMapping(blockCodeID, districtCodeID) VALUES('119276','102109');
INSERT INTO evt_districtBlockMapping(blockCodeID, districtCodeID) VALUES('119277','102109');
INSERT INTO evt_districtBlockMapping(blockCodeID, districtCodeID) VALUES('119278','102107');
INSERT INTO evt_districtBlockMapping(blockCodeID, districtCodeID) VALUES('119279','102107');
INSERT INTO evt_districtBlockMapping(blockCodeID, districtCodeID) VALUES('119280','102107');
INSERT INTO evt_districtBlockMapping(blockCodeID, districtCodeID) VALUES('119281','102107');
INSERT INTO evt_districtBlockMapping(blockCodeID, districtCodeID) VALUES('119282','102107');
INSERT INTO evt_districtBlockMapping(blockCodeID, districtCodeID) VALUES('119283','102107');
INSERT INTO evt_districtBlockMapping(blockCodeID, districtCodeID) VALUES('119284','102107');
INSERT INTO evt_districtBlockMapping(blockCodeID, districtCodeID) VALUES('119285','102107');
INSERT INTO evt_districtBlockMapping(blockCodeID, districtCodeID) VALUES('119286','102107');
INSERT INTO evt_districtBlockMapping(blockCodeID, districtCodeID) VALUES('119287','102107');
INSERT INTO evt_districtBlockMapping(blockCodeID, districtCodeID) VALUES('119288','102107');
INSERT INTO evt_districtBlockMapping(blockCodeID, districtCodeID) VALUES('119289','102107');
INSERT INTO evt_districtBlockMapping(blockCodeID, districtCodeID) VALUES('119290','102107');
INSERT INTO evt_districtBlockMapping(blockCodeID, districtCodeID) VALUES('119291','102107');
INSERT INTO evt_districtBlockMapping(blockCodeID, districtCodeID) VALUES('119292','102107');
INSERT INTO evt_districtBlockMapping(blockCodeID, districtCodeID) VALUES('119293','102134');
INSERT INTO evt_districtBlockMapping(blockCodeID, districtCodeID) VALUES('119294','102134');
INSERT INTO evt_districtBlockMapping(blockCodeID, districtCodeID) VALUES('119295','102134');
INSERT INTO evt_districtBlockMapping(blockCodeID, districtCodeID) VALUES('119296','102134');
INSERT INTO evt_districtBlockMapping(blockCodeID, districtCodeID) VALUES('119297','102134');
INSERT INTO evt_districtBlockMapping(blockCodeID, districtCodeID) VALUES('119298','102134');
INSERT INTO evt_districtBlockMapping(blockCodeID, districtCodeID) VALUES('119299','102134');
INSERT INTO evt_districtBlockMapping(blockCodeID, districtCodeID) VALUES('119300','102134');
INSERT INTO evt_districtBlockMapping(blockCodeID, districtCodeID) VALUES('119301','102134');
INSERT INTO evt_districtBlockMapping(blockCodeID, districtCodeID) VALUES('119302','102134');
INSERT INTO evt_districtBlockMapping(blockCodeID, districtCodeID) VALUES('119303','102134');
INSERT INTO evt_districtBlockMapping(blockCodeID, districtCodeID) VALUES('119304','102134');
INSERT INTO evt_districtBlockMapping(blockCodeID, districtCodeID) VALUES('119305','102134');
INSERT INTO evt_districtBlockMapping(blockCodeID, districtCodeID) VALUES('119306','102134');
INSERT INTO evt_districtBlockMapping(blockCodeID, districtCodeID) VALUES('119307','102134');
INSERT INTO evt_districtBlockMapping(blockCodeID, districtCodeID) VALUES('119308','102134');
INSERT INTO evt_districtBlockMapping(blockCodeID, districtCodeID) VALUES('119309','102119');
INSERT INTO evt_districtBlockMapping(blockCodeID, districtCodeID) VALUES('119310','102119');
INSERT INTO evt_districtBlockMapping(blockCodeID, districtCodeID) VALUES('119311','102119');
INSERT INTO evt_districtBlockMapping(blockCodeID, districtCodeID) VALUES('119312','102119');
INSERT INTO evt_districtBlockMapping(blockCodeID, districtCodeID) VALUES('119313','102119');
INSERT INTO evt_districtBlockMapping(blockCodeID, districtCodeID) VALUES('119314','102119');
INSERT INTO evt_districtBlockMapping(blockCodeID, districtCodeID) VALUES('119315','102119');
INSERT INTO evt_districtBlockMapping(blockCodeID, districtCodeID) VALUES('119316','102119');
INSERT INTO evt_districtBlockMapping(blockCodeID, districtCodeID) VALUES('119317','102119');
INSERT INTO evt_districtBlockMapping(blockCodeID, districtCodeID) VALUES('119318','102119');
INSERT INTO evt_districtBlockMapping(blockCodeID, districtCodeID) VALUES('119319','102119');
INSERT INTO evt_districtBlockMapping(blockCodeID, districtCodeID) VALUES('119320','102119');
INSERT INTO evt_districtBlockMapping(blockCodeID, districtCodeID) VALUES('119321','102119');
INSERT INTO evt_districtBlockMapping(blockCodeID, districtCodeID) VALUES('119322','102119');
INSERT INTO evt_districtBlockMapping(blockCodeID, districtCodeID) VALUES('119323','102119');
INSERT INTO evt_districtBlockMapping(blockCodeID, districtCodeID) VALUES('119324','102119');
INSERT INTO evt_districtBlockMapping(blockCodeID, districtCodeID) VALUES('119325','102111');
INSERT INTO evt_districtBlockMapping(blockCodeID, districtCodeID) VALUES('119326','102111');
INSERT INTO evt_districtBlockMapping(blockCodeID, districtCodeID) VALUES('119327','102111');
INSERT INTO evt_districtBlockMapping(blockCodeID, districtCodeID) VALUES('119328','102111');
INSERT INTO evt_districtBlockMapping(blockCodeID, districtCodeID) VALUES('119329','102111');
INSERT INTO evt_districtBlockMapping(blockCodeID, districtCodeID) VALUES('119330','102123');
INSERT INTO evt_districtBlockMapping(blockCodeID, districtCodeID) VALUES('119331','102123');
INSERT INTO evt_districtBlockMapping(blockCodeID, districtCodeID) VALUES('119332','102123');
INSERT INTO evt_districtBlockMapping(blockCodeID, districtCodeID) VALUES('119333','102123');
INSERT INTO evt_districtBlockMapping(blockCodeID, districtCodeID) VALUES('119334','102123');
INSERT INTO evt_districtBlockMapping(blockCodeID, districtCodeID) VALUES('119335','102123');
INSERT INTO evt_districtBlockMapping(blockCodeID, districtCodeID) VALUES('119336','102123');
INSERT INTO evt_districtBlockMapping(blockCodeID, districtCodeID) VALUES('119337','102123');
INSERT INTO evt_districtBlockMapping(blockCodeID, districtCodeID) VALUES('119338','102123');
INSERT INTO evt_districtBlockMapping(blockCodeID, districtCodeID) VALUES('119339','102113');
INSERT INTO evt_districtBlockMapping(blockCodeID, districtCodeID) VALUES('119340','102113');
INSERT INTO evt_districtBlockMapping(blockCodeID, districtCodeID) VALUES('119341','102113');
INSERT INTO evt_districtBlockMapping(blockCodeID, districtCodeID) VALUES('119342','102113');
INSERT INTO evt_districtBlockMapping(blockCodeID, districtCodeID) VALUES('119343','102113');
INSERT INTO evt_districtBlockMapping(blockCodeID, districtCodeID) VALUES('119344','102113');
INSERT INTO evt_districtBlockMapping(blockCodeID, districtCodeID) VALUES('119345','102113');
INSERT INTO evt_districtBlockMapping(blockCodeID, districtCodeID) VALUES('119346','102113');
INSERT INTO evt_districtBlockMapping(blockCodeID, districtCodeID) VALUES('119347','102103');
INSERT INTO evt_districtBlockMapping(blockCodeID, districtCodeID) VALUES('119348','102103');
INSERT INTO evt_districtBlockMapping(blockCodeID, districtCodeID) VALUES('119349','102103');
INSERT INTO evt_districtBlockMapping(blockCodeID, districtCodeID) VALUES('119350','102103');
INSERT INTO evt_districtBlockMapping(blockCodeID, districtCodeID) VALUES('119351','102103');
INSERT INTO evt_districtBlockMapping(blockCodeID, districtCodeID) VALUES('119352','102103');
INSERT INTO evt_districtBlockMapping(blockCodeID, districtCodeID) VALUES('119353','102103');
INSERT INTO evt_districtBlockMapping(blockCodeID, districtCodeID) VALUES('119354','102103');
INSERT INTO evt_districtBlockMapping(blockCodeID, districtCodeID) VALUES('119355','102103');
INSERT INTO evt_districtBlockMapping(blockCodeID, districtCodeID) VALUES('119356','102104');
INSERT INTO evt_districtBlockMapping(blockCodeID, districtCodeID) VALUES('119357','102104');
INSERT INTO evt_districtBlockMapping(blockCodeID, districtCodeID) VALUES('119358','102104');
INSERT INTO evt_districtBlockMapping(blockCodeID, districtCodeID) VALUES('119359','102104');
INSERT INTO evt_districtBlockMapping(blockCodeID, districtCodeID) VALUES('119360','102104');
INSERT INTO evt_districtBlockMapping(blockCodeID, districtCodeID) VALUES('119361','102104');
INSERT INTO evt_districtBlockMapping(blockCodeID, districtCodeID) VALUES('119362','102104');
INSERT INTO evt_districtBlockMapping(blockCodeID, districtCodeID) VALUES('119363','102104');
INSERT INTO evt_districtBlockMapping(blockCodeID, districtCodeID) VALUES('119364','102104');
INSERT INTO evt_districtBlockMapping(blockCodeID, districtCodeID) VALUES('119365','102104');
INSERT INTO evt_districtBlockMapping(blockCodeID, districtCodeID) VALUES('119366','102104');
INSERT INTO evt_districtBlockMapping(blockCodeID, districtCodeID) VALUES('119367','102115');
INSERT INTO evt_districtBlockMapping(blockCodeID, districtCodeID) VALUES('119368','102115');
INSERT INTO evt_districtBlockMapping(blockCodeID, districtCodeID) VALUES('119369','102115');
INSERT INTO evt_districtBlockMapping(blockCodeID, districtCodeID) VALUES('119370','102115');
INSERT INTO evt_districtBlockMapping(blockCodeID, districtCodeID) VALUES('119371','102115');
INSERT INTO evt_districtBlockMapping(blockCodeID, districtCodeID) VALUES('119372','102115');
INSERT INTO evt_districtBlockMapping(blockCodeID, districtCodeID) VALUES('119373','102115');
INSERT INTO evt_districtBlockMapping(blockCodeID, districtCodeID) VALUES('119374','102115');
INSERT INTO evt_districtBlockMapping(blockCodeID, districtCodeID) VALUES('119375','102115');
INSERT INTO evt_districtBlockMapping(blockCodeID, districtCodeID) VALUES('119376','102115');
INSERT INTO evt_districtBlockMapping(blockCodeID, districtCodeID) VALUES('119377','102122');
INSERT INTO evt_districtBlockMapping(blockCodeID, districtCodeID) VALUES('119378','102122');
INSERT INTO evt_districtBlockMapping(blockCodeID, districtCodeID) VALUES('119379','102122');
INSERT INTO evt_districtBlockMapping(blockCodeID, districtCodeID) VALUES('119380','102122');
INSERT INTO evt_districtBlockMapping(blockCodeID, districtCodeID) VALUES('119381','102122');
INSERT INTO evt_districtBlockMapping(blockCodeID, districtCodeID) VALUES('119382','102122');
INSERT INTO evt_districtBlockMapping(blockCodeID, districtCodeID) VALUES('119383','102122');
INSERT INTO evt_districtBlockMapping(blockCodeID, districtCodeID) VALUES('119384','102122');
INSERT INTO evt_districtBlockMapping(blockCodeID, districtCodeID) VALUES('119385','102130');
INSERT INTO evt_districtBlockMapping(blockCodeID, districtCodeID) VALUES('119386','102130');
INSERT INTO evt_districtBlockMapping(blockCodeID, districtCodeID) VALUES('119387','102130');
INSERT INTO evt_districtBlockMapping(blockCodeID, districtCodeID) VALUES('119388','102130');
INSERT INTO evt_districtBlockMapping(blockCodeID, districtCodeID) VALUES('119389','102130');
INSERT INTO evt_districtBlockMapping(blockCodeID, districtCodeID) VALUES('119390','102130');
INSERT INTO evt_districtBlockMapping(blockCodeID, districtCodeID) VALUES('119391','102130');
INSERT INTO evt_districtBlockMapping(blockCodeID, districtCodeID) VALUES('119392','102130');
INSERT INTO evt_districtBlockMapping(blockCodeID, districtCodeID) VALUES('119393','102130');
INSERT INTO evt_districtBlockMapping(blockCodeID, districtCodeID) VALUES('119394','102130');
INSERT INTO evt_districtBlockMapping(blockCodeID, districtCodeID) VALUES('119395','102130');
INSERT INTO evt_districtBlockMapping(blockCodeID, districtCodeID) VALUES('119396','102100');
INSERT INTO evt_districtBlockMapping(blockCodeID, districtCodeID) VALUES('119397','102100');
INSERT INTO evt_districtBlockMapping(blockCodeID, districtCodeID) VALUES('119398','102100');
INSERT INTO evt_districtBlockMapping(blockCodeID, districtCodeID) VALUES('119399','102100');
INSERT INTO evt_districtBlockMapping(blockCodeID, districtCodeID) VALUES('119400','102100');
INSERT INTO evt_districtBlockMapping(blockCodeID, districtCodeID) VALUES('119401','102100');
INSERT INTO evt_districtBlockMapping(blockCodeID, districtCodeID) VALUES('119402','102100');
INSERT INTO evt_districtBlockMapping(blockCodeID, districtCodeID) VALUES('119403','102100');
INSERT INTO evt_districtBlockMapping(blockCodeID, districtCodeID) VALUES('119404','102100');
INSERT INTO evt_districtBlockMapping(blockCodeID, districtCodeID) VALUES('119405','102100');
INSERT INTO evt_districtBlockMapping(blockCodeID, districtCodeID) VALUES('119406','102100');
INSERT INTO evt_districtBlockMapping(blockCodeID, districtCodeID) VALUES('119407','102100');
INSERT INTO evt_districtBlockMapping(blockCodeID, districtCodeID) VALUES('119408','102100');
INSERT INTO evt_districtBlockMapping(blockCodeID, districtCodeID) VALUES('119409','102100');
INSERT INTO evt_districtBlockMapping(blockCodeID, districtCodeID) VALUES('119410','102124');
INSERT INTO evt_districtBlockMapping(blockCodeID, districtCodeID) VALUES('119411','102124');
INSERT INTO evt_districtBlockMapping(blockCodeID, districtCodeID) VALUES('119412','102124');
INSERT INTO evt_districtBlockMapping(blockCodeID, districtCodeID) VALUES('119413','102124');
INSERT INTO evt_districtBlockMapping(blockCodeID, districtCodeID) VALUES('119414','102124');
INSERT INTO evt_districtBlockMapping(blockCodeID, districtCodeID) VALUES('119415','102124');
INSERT INTO evt_districtBlockMapping(blockCodeID, districtCodeID) VALUES('119416','102124');
INSERT INTO evt_districtBlockMapping(blockCodeID, districtCodeID) VALUES('119417','102124');
INSERT INTO evt_districtBlockMapping(blockCodeID, districtCodeID) VALUES('119418','102124');
INSERT INTO evt_districtBlockMapping(blockCodeID, districtCodeID) VALUES('119419','102124');
INSERT INTO evt_districtBlockMapping(blockCodeID, districtCodeID) VALUES('119420','102124');
INSERT INTO evt_districtBlockMapping(blockCodeID, districtCodeID) VALUES('119421','102124');
INSERT INTO evt_districtBlockMapping(blockCodeID, districtCodeID) VALUES('119422','102124');
INSERT INTO evt_districtBlockMapping(blockCodeID, districtCodeID) VALUES('119423','102124');
INSERT INTO evt_districtBlockMapping(blockCodeID, districtCodeID) VALUES('119424','102128');
INSERT INTO evt_districtBlockMapping(blockCodeID, districtCodeID) VALUES('119425','102128');
INSERT INTO evt_districtBlockMapping(blockCodeID, districtCodeID) VALUES('119426','102128');
INSERT INTO evt_districtBlockMapping(blockCodeID, districtCodeID) VALUES('119427','102128');
INSERT INTO evt_districtBlockMapping(blockCodeID, districtCodeID) VALUES('119428','102128');
INSERT INTO evt_districtBlockMapping(blockCodeID, districtCodeID) VALUES('119429','102128');
INSERT INTO evt_districtBlockMapping(blockCodeID, districtCodeID) VALUES('119430','102128');
INSERT INTO evt_districtBlockMapping(blockCodeID, districtCodeID) VALUES('119431','102128');
INSERT INTO evt_districtBlockMapping(blockCodeID, districtCodeID) VALUES('119432','102128');
INSERT INTO evt_districtBlockMapping(blockCodeID, districtCodeID) VALUES('119433','102128');
INSERT INTO evt_districtBlockMapping(blockCodeID, districtCodeID) VALUES('119434','102128');
INSERT INTO evt_districtBlockMapping(blockCodeID, districtCodeID) VALUES('119435','102127');
INSERT INTO evt_districtBlockMapping(blockCodeID, districtCodeID) VALUES('119436','102127');
INSERT INTO evt_districtBlockMapping(blockCodeID, districtCodeID) VALUES('119437','102127');
INSERT INTO evt_districtBlockMapping(blockCodeID, districtCodeID) VALUES('119438','102127');
INSERT INTO evt_districtBlockMapping(blockCodeID, districtCodeID) VALUES('119439','102127');
INSERT INTO evt_districtBlockMapping(blockCodeID, districtCodeID) VALUES('119440','102127');
INSERT INTO evt_districtBlockMapping(blockCodeID, districtCodeID) VALUES('119441','102127');
INSERT INTO evt_districtBlockMapping(blockCodeID, districtCodeID) VALUES('119442','102127');
INSERT INTO evt_districtBlockMapping(blockCodeID, districtCodeID) VALUES('119443','102127');
INSERT INTO evt_districtBlockMapping(blockCodeID, districtCodeID) VALUES('119444','102127');
INSERT INTO evt_districtBlockMapping(blockCodeID, districtCodeID) VALUES('119445','102114');
INSERT INTO evt_districtBlockMapping(blockCodeID, districtCodeID) VALUES('119446','102114');
INSERT INTO evt_districtBlockMapping(blockCodeID, districtCodeID) VALUES('119447','102114');
INSERT INTO evt_districtBlockMapping(blockCodeID, districtCodeID) VALUES('119448','102114');
INSERT INTO evt_districtBlockMapping(blockCodeID, districtCodeID) VALUES('119449','102114');
INSERT INTO evt_districtBlockMapping(blockCodeID, districtCodeID) VALUES('119450','102114');
INSERT INTO evt_districtBlockMapping(blockCodeID, districtCodeID) VALUES('119451','102114');
INSERT INTO evt_districtBlockMapping(blockCodeID, districtCodeID) VALUES('119452','102114');
INSERT INTO evt_districtBlockMapping(blockCodeID, districtCodeID) VALUES('119453','102114');
INSERT INTO evt_districtBlockMapping(blockCodeID, districtCodeID) VALUES('119454','102114');
INSERT INTO evt_districtBlockMapping(blockCodeID, districtCodeID) VALUES('119455','102114');
INSERT INTO evt_districtBlockMapping(blockCodeID, districtCodeID) VALUES('119456','102114');

-- Insert code group for Calendar.
Insert into com_codeGroup (codeGroupID, codeGroupName, createdBy, createdOn, modifiedBy, modifiedOn)
Select 120 as codeGroupID, 'Training Status' as codeGroupName, 1 as createdBy, now() as createdOn,  1 as modifiedBy, now() as modifiedOn;

-- Insert into code - Training Status
Insert into com_code (codeID, codeGroupID, codeNameEn, codeNameMr, createdBy, createdOn, modifiedBy, modifiedOn)
Select 120100 as codeID, 120 as codeGroupID, 'Published' as codeNameEn, '' as codeNameMr, 1 as createdBy, now() as createdOn,  1 as modifiedBy, now() as modifiedOn union 
Select 120101 as codeID, 120 as codeGroupID, 'Cancelled ' as codeNameEn, '' as codeNameMr, 1 as createdBy, now() as createdOn,  1 as modifiedBy, now() as modifiedOn;


-- update com code version.
update com_configuration set value = value + 1 where `key` = 'comCodeVersion';

-- update into com_configuration
update com_configuration set `value` = '73-mitraDBAddBlocks' where `key` = 'dbScriptExecutedUntil';







