# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-18 11:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='district',
            fields=[
                ('districtID', models.IntegerField(primary_key=True, serialize=False)),
                ('districtName', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'db_table': 'com_District',
                'get_latest_by': 'districtName',
            },
        ),
    ]
