# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-16 13:11
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='language',
            fields=[
                ('languageID', models.AutoField(primary_key=True, serialize=False)),
                ('languageName', models.CharField(max_length=256)),
                ('resourceCode', models.CharField(max_length=3)),
                ('createdOn', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'com_Language',
                'get_latest_by': 'userName',
            },
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('userID', models.AutoField(primary_key=True, serialize=False)),
                ('phoneNumber', models.CharField(max_length=15, unique=True, validators=[django.core.validators.RegexValidator(message=b"Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex=b'^\\+?1?\\d{9,15}$')])),
                ('userName', models.CharField(max_length=100, null=True)),
                ('photoUrl', models.CharField(max_length=255, null=True)),
                ('udiseCode', models.CharField(max_length=255, null=True)),
                ('emailID', models.EmailField(max_length=100, null=True)),
                ('createdOn', models.DateTimeField(default=django.utils.timezone.now)),
                ('modifiedOn', models.DateTimeField(default=django.utils.timezone.now)),
                ('createdBy', models.ForeignKey(db_column=b'createdBy', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_createdBy', to='appUser.user')),
                ('modifiedBy', models.ForeignKey(db_column=b'modifiedBy', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_modifiedBy', to='appUser.user')),
                ('preferredLanguageID', models.ForeignKey(db_column=b'languageID', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_preferredLanguageID', to='appUser.language')),
            ],
            options={
                'db_table': 'usr_User',
                'get_latest_by': 'userName',
            },
        ),
        migrations.CreateModel(
            name='userAuth',
            fields=[
                ('userAuthID', models.AutoField(primary_key=True, serialize=False)),
                ('loginID', models.IntegerField(unique=True)),
                ('passwordOTP', models.CharField(max_length=6, null=True)),
                ('password', models.CharField(max_length=256, null=True)),
                ('sessionToken', models.CharField(max_length=256, null=True)),
                ('lastLoggedInOn', models.DateTimeField(default=django.utils.timezone.now)),
                ('createdOn', models.DateTimeField(default=django.utils.timezone.now)),
                ('modifiedOn', models.DateTimeField(default=django.utils.timezone.now)),
                ('createdBy', models.ForeignKey(db_column=b'createdBy', on_delete=django.db.models.deletion.CASCADE, related_name='userAuth_createdBy', to='appUser.user')),
                ('modifiedBy', models.ForeignKey(db_column=b'modifiedBy', on_delete=django.db.models.deletion.CASCADE, related_name='userAuth_modifiedBy', to='appUser.user')),
            ],
            options={
                'db_table': 'usr_userAuth',
            },
        ),
        migrations.AddField(
            model_name='language',
            name='createdBy',
            field=models.ForeignKey(db_column=b'createdBy', on_delete=django.db.models.deletion.CASCADE, related_name='language_createdBy', to='appUser.user'),
        ),
    ]
